//! civ-protocol-3d — WebSocket binary protocol extensions for the Civis 3D layer.
//!
//! Extends the existing Civis WebSocket JSON-RPC + binary protocol (ADR-003) with
//! frame types for:
//!
//! - **Voxel deltas** — drained `DirtyChunkEvent` batches plus the chunk content
//!   needed to re-mesh on the client side.
//! - **Building diffs** — `BuildingGraph` mutations tagged with provenance
//!   (procedural vs freehand).
//! - **Agent appearance** — per-civilian wardrobe / tools state updates.
//!
//! This crate currently ships the wire-format types and a versioning gate; the
//! actual binary serialisation (zstd-compressed frames) and WebSocket attach
//! happen in `civ-server` once the frame types stabilise.
//!
//! See `docs/development-guide/fr-3d-additions.md` for `FR-CIV-PROTO3D-*`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use serde::{Deserialize, Serialize};

pub use civ_voxel::{ChunkId, DirtyChunkEvent, MaterialId, WriteSeq};

/// Schema version of the public protocol-3d frame types. Bumped on any
/// wire-incompatible change; clients refuse to attach on mismatch.
pub const SCHEMA_VERSION: u32 = 0;

/// Provenance tag carried by every building diff so the renderer can style
/// procedural-grown vs user-freehand structures differently if desired.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BuildingProvenance {
    /// Generated by the autonomous demand-driven allocator.
    Procedural,
    /// Authored by the user in freehand mode.
    Freehand,
}

/// One delta event for a single chunk. The renderer pairs `event` with the
/// `voxels` payload to re-mesh the affected chunk.
///
/// Wire layout: `event` is ~24 bytes (ChunkId u64 + WriteSeq u64 + bounds in a
/// follow-up). `voxels` is the dense leaf payload (`16^3 = 4096` voxels) packed
/// as `MaterialId` u16s = 8 KiB per dirty chunk before zstd. Practical
/// production framing will be either:
///
/// - Delta-encoded RLE over `voxels` for cheap chunks
/// - Whole-chunk replacement for fully-edited chunks
///
/// Both encodings ride on top of this type; the encoding tag lands in the
/// follow-up PR that introduces the wire format.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VoxelChunkDelta {
    /// The drained dirty event that triggered this delta.
    pub event: DirtyChunkEvent,
    /// Full dense-leaf voxel payload for the affected chunk.
    pub voxels: Vec<MaterialId>,
}

/// A batch of voxel deltas delivered after one server tick. The batch is always
/// pre-sorted by `(chunk_id, write_seq)` (the kernel guarantees this via
/// `VoxelWorld::drain_dirty`); clients can rely on iteration order being
/// identical across machines.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct VoxelDeltaFrame {
    /// Server tick at which the batch was produced.
    pub tick: u64,
    /// One entry per affected chunk.
    pub deltas: Vec<VoxelChunkDelta>,
}

/// Building-diff frame. The actual `BuildingGraph` payload is supplied by
/// `civ-build` in a future PR (the type is reserved here so renderers can
/// recognise the frame kind before the schema lands).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BuildingDiffFrame {
    /// Server tick at which the diff was produced.
    pub tick: u64,
    /// Provenance of every mutation in this frame (mixed-provenance frames
    /// carry the dominant provenance — finer per-mutation tagging lives inside
    /// the `BuildingGraph` payload itself once it lands).
    pub provenance: BuildingProvenance,
}

/// Agent appearance update — one entry per agent whose visible state changed
/// this tick (wardrobe, tools, era).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentAppearanceFrame {
    /// Server tick at which the update was produced.
    pub tick: u64,
    /// One entry per agent whose appearance changed.
    pub updates: Vec<AgentAppearanceUpdate>,
}

/// A single per-agent appearance state update.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentAppearanceUpdate {
    /// Opaque ECS entity ID. The server side ensures stable IDs across ticks.
    pub agent_id: u64,
    /// Era index — drives the diffusion-curve-driven facade/wardrobe rendering.
    pub era: u16,
    /// Wardrobe material slot.
    pub wardrobe: MaterialId,
    /// Tools material slot.
    pub tools: MaterialId,
}

/// Discriminated union of all 3D-extension protocol frames. The existing Civis
/// protocol carries this inside its binary-frame envelope.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Frame3d {
    /// Voxel-delta batch for one tick.
    VoxelDelta(VoxelDeltaFrame),
    /// Building-diff batch for one tick.
    BuildingDiff(BuildingDiffFrame),
    /// Agent appearance batch for one tick.
    AgentAppearance(AgentAppearanceFrame),
}

impl Frame3d {
    /// Server tick this frame was produced at.
    #[must_use]
    pub fn tick(&self) -> u64 {
        match self {
            Self::VoxelDelta(f) => f.tick,
            Self::BuildingDiff(f) => f.tick,
            Self::AgentAppearance(f) => f.tick,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// FR-CIV-PROTO3D-000 — schema version is exposed.
    #[test]
    fn schema_version_present() {
        assert_eq!(SCHEMA_VERSION, 0);
    }

    /// FR-CIV-PROTO3D-001 — VoxelDeltaFrame round-trips through serde JSON
    /// losslessly. Binary framing lands in a follow-up PR but JSON is a useful
    /// determinism floor.
    #[test]
    fn voxel_delta_frame_roundtrips() {
        let frame = VoxelDeltaFrame {
            tick: 42,
            deltas: vec![VoxelChunkDelta {
                event: DirtyChunkEvent {
                    chunk_id: ChunkId(7),
                    write_seq: WriteSeq(3),
                },
                voxels: vec![MaterialId(0); 16 * 16 * 16],
            }],
        };
        let s = serde_json::to_string(&frame).expect("serialize");
        let back: VoxelDeltaFrame = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(frame, back);
    }

    /// FR-CIV-PROTO3D-002 — building diff carries provenance.
    #[test]
    fn building_diff_carries_provenance() {
        let f = BuildingDiffFrame {
            tick: 100,
            provenance: BuildingProvenance::Freehand,
        };
        let s = serde_json::to_string(&f).expect("serialize");
        let back: BuildingDiffFrame = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(back.provenance, BuildingProvenance::Freehand);
    }

    /// FR-CIV-PROTO3D-003 — Frame3d::tick exposes the inner tick.
    #[test]
    fn frame3d_tick_extraction() {
        let f = Frame3d::VoxelDelta(VoxelDeltaFrame {
            tick: 17,
            deltas: Vec::new(),
        });
        assert_eq!(f.tick(), 17);
    }
}
