//! civ-protocol-3d — WebSocket binary protocol extensions for the Civis 3D layer.
//!
//! Extends the existing Civis WebSocket JSON-RPC + binary protocol (ADR-003) with
//! frame types for:
//!
//! - **Voxel deltas** — drained `DirtyChunkEvent` batches plus the chunk content
//!   needed to re-mesh on the client side.
//! - **Building diffs** — `BuildingGraph` mutations tagged with provenance
//!   (procedural vs freehand).
//! - **Agent appearance** — per-civilian wardrobe / tools state updates.
//!
//! This crate ships the wire-format types, a versioning gate, and a minimal
//! length-prefixed binary envelope (`encode_frame3d_binary` / `decode_frame3d_binary`).
//! Full zstd-compressed production framing and WebSocket attach land in
//! `civ-server` once the schema stabilises.
//!
//! **Tick batch coalescing:** the server sends three separate `F3D0` frames per
//! tick (voxel, building, agent) rather than one length-prefixed batch blob.
//! Clients already decode individual frames; merging them would require a new
//! magic/batch envelope and break existing decoders for a small WebSocket
//! framing win (3 headers ≈ 27 bytes vs 1).
//!
//! See `docs/development-guide/fr-3d-additions.md` for `FR-CIV-PROTO3D-*`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use serde::{Deserialize, Serialize};

pub use civ_voxel::{ChunkId, DirtyChunkEvent, MaterialId, WriteSeq};

/// Schema version of the public protocol-3d frame types. Bumped on any
/// wire-incompatible change; clients refuse to attach on mismatch.
pub const SCHEMA_VERSION: u32 = 0;

/// Provenance tag carried by every building diff so the renderer can style
/// procedural-grown vs user-freehand structures differently if desired.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BuildingProvenance {
    /// Generated by the autonomous demand-driven allocator.
    Procedural,
    /// Authored by the user in freehand mode.
    Freehand,
}

/// World-space X/Z anchor in Bevy terrain units (fixed-scale coords / [`civ_voxel::FIXED_SCALE`]).
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct WorldXZ {
    /// World X in the same units as the Bevy standalone terrain mesh.
    pub x: f32,
    /// World Z in the same units as the Bevy standalone terrain mesh.
    pub z: f32,
}

impl WorldXZ {
    /// Convert a fixed-point [`WorldCoord`] into Bevy terrain units.
    #[must_use]
    pub fn from_fixed_coord(coord: &civ_voxel::WorldCoord) -> Self {
        let scale = civ_voxel::FIXED_SCALE as f32;
        Self {
            x: coord.x as f32 / scale,
            z: coord.z as f32 / scale,
        }
    }
}

/// Building kind mirrored for wire payloads (matches `civ_engine::BuildingType` labels).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BuildingKind3d {
    /// Farm parcel.
    Farm,
    /// Mine parcel.
    Mine,
    /// Barracks parcel.
    Barracks,
    /// Temple parcel.
    Temple,
    /// Market parcel.
    Market,
    /// House parcel.
    House,
    /// City center parcel.
    CityCenter,
}

/// One building entry carried in a [`BuildingDiffFrame`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BuildingDiffEntry {
    /// Stable building entity id from the simulation ECS.
    pub id: u64,
    /// Building classification for client-side styling.
    pub kind: BuildingKind3d,
    /// World-space anchor for the building marker mesh.
    pub position: WorldXZ,
}

/// Building-diff frame. Carries provenance plus optional building snapshots for renderers.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BuildingDiffFrame {
    /// Server tick at which the diff was produced.
    pub tick: u64,
    /// Provenance of every mutation in this frame (mixed-provenance frames
    /// carry the dominant provenance — finer per-mutation tagging lives inside
    /// the `BuildingGraph` payload itself once it lands).
    pub provenance: BuildingProvenance,
    /// Buildings visible this tick (full snapshot; empty on legacy servers).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub buildings: Vec<BuildingDiffEntry>,
}

/// One delta event for a single chunk. The renderer pairs `event` with the
/// `voxels` payload to re-mesh the affected chunk.
///
/// Wire layout: `event` is ~24 bytes (ChunkId u64 + WriteSeq u64 + bounds in a
/// follow-up). `voxels` is the dense leaf payload (`16^3 = 4096` voxels) packed
/// as `MaterialId` u16s = 8 KiB per dirty chunk before zstd. Practical
/// production framing will be either:
///
/// - Delta-encoded RLE over `voxels` for cheap chunks
/// - Whole-chunk replacement for fully-edited chunks
///
/// Both encodings ride on top of this type; the encoding tag lands in the
/// follow-up PR that introduces the wire format.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VoxelChunkDelta {
    /// The drained dirty event that triggered this delta.
    pub event: DirtyChunkEvent,
    /// Full dense-leaf voxel payload for the affected chunk.
    pub voxels: Vec<MaterialId>,
}

/// A batch of voxel deltas delivered after one server tick. The batch is always
/// pre-sorted by `(chunk_id, write_seq)` (the kernel guarantees this via
/// `VoxelWorld::drain_dirty`); clients can rely on iteration order being
/// identical across machines.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct VoxelDeltaFrame {
    /// Server tick at which the batch was produced.
    pub tick: u64,
    /// One entry per affected chunk.
    pub deltas: Vec<VoxelChunkDelta>,
}

/// Agent appearance update — one entry per agent whose visible state changed
/// this tick (wardrobe, tools, era).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentAppearanceFrame {
    /// Server tick at which the update was produced.
    pub tick: u64,
    /// One entry per agent whose appearance changed.
    pub updates: Vec<AgentAppearanceUpdate>,
}

/// A single per-agent appearance state update.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentAppearanceUpdate {
    /// Opaque ECS entity ID. The server side ensures stable IDs across ticks.
    pub agent_id: u64,
    /// Era index — drives the diffusion-curve-driven facade/wardrobe rendering.
    pub era: u16,
    /// Wardrobe material slot.
    pub wardrobe: MaterialId,
    /// Tools material slot.
    pub tools: MaterialId,
    /// Uniform scale multiplier for the agent marker mesh (`1.0` when omitted).
    #[serde(default = "default_agent_scale")]
    pub scale: f32,
    /// World-space anchor when the server knows agent ECS position (item 29+).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position: Option<WorldXZ>,
}

fn default_agent_scale() -> f32 {
    1.0
}

/// Discriminated union of all 3D-extension protocol frames. The existing Civis
/// protocol carries this inside its binary-frame envelope.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Frame3d {
    /// Voxel-delta batch for one tick.
    VoxelDelta(VoxelDeltaFrame),
    /// Building-diff batch for one tick.
    BuildingDiff(BuildingDiffFrame),
    /// Agent appearance batch for one tick.
    AgentAppearance(AgentAppearanceFrame),
}

impl Frame3d {
    /// Server tick this frame was produced at.
    #[must_use]
    pub fn tick(&self) -> u64 {
        match self {
            Self::VoxelDelta(f) => f.tick,
            Self::BuildingDiff(f) => f.tick,
            Self::AgentAppearance(f) => f.tick,
        }
    }
}

/// Resolve agent world translation for 3D clients (legacy fallback uses `agent_id` on X).
#[must_use]
pub fn agent_world_translation(update: &AgentAppearanceUpdate, y: f32) -> (f32, f32, f32) {
    if let Some(pos) = update.position {
        (pos.x, y, pos.z)
    } else {
        (update.agent_id as f32, y, 0.0)
    }
}

/// 4-byte magic identifying civ-protocol-3d binary frames (CIV-0200 partial).
pub const FRAME3D_BINARY_MAGIC: &[u8; 4] = b"F3D0";

/// Header size: magic (4) + kind tag (1) + payload length (4, big-endian).
const FRAME3D_BINARY_HEADER_LEN: usize = 9;

/// Variant tag carried in the binary header (kind byte).
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Frame3dKind {
    VoxelDelta = 0,
    BuildingDiff = 1,
    AgentAppearance = 2,
}

impl Frame3dKind {
    fn from_frame(frame: &Frame3d) -> Self {
        match frame {
            Frame3d::VoxelDelta(_) => Self::VoxelDelta,
            Frame3d::BuildingDiff(_) => Self::BuildingDiff,
            Frame3d::AgentAppearance(_) => Self::AgentAppearance,
        }
    }
}

/// Errors from binary frame encode/decode.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Frame3dBinaryError {
    /// Magic bytes do not match [`FRAME3D_BINARY_MAGIC`].
    BadMagic,
    /// Buffer is shorter than the fixed header.
    TooShort,
    /// Declared payload length does not match the buffer.
    LengthMismatch,
    /// JSON payload could not be serialized or parsed.
    InvalidPayload(String),
}

/// Encode a [`Frame3d`] as `magic || kind || len_be || json`.
///
/// JSON carries the full tagged union so clients can reuse existing serde
/// schemas while the binary envelope satisfies CIV-0200 binary-frame clients.
pub fn encode_frame3d_binary(frame: &Frame3d) -> Result<Vec<u8>, Frame3dBinaryError> {
    let json = serde_json::to_vec(frame)
        .map_err(|err| Frame3dBinaryError::InvalidPayload(err.to_string()))?;
    encode_frame3d_binary_from_json(frame, &json)
}

/// Wrap already-serialized JSON bytes in the `F3D0` envelope for `frame`.
///
/// Use when the same JSON is sent as a WebSocket text frame and as the binary
/// payload (avoids a second `serde_json` pass in `Both` tick-broadcast mode).
pub fn encode_frame3d_binary_from_json(
    frame: &Frame3d,
    json: &[u8],
) -> Result<Vec<u8>, Frame3dBinaryError> {
    let kind = Frame3dKind::from_frame(frame);
    let len = u32::try_from(json.len()).map_err(|_| Frame3dBinaryError::LengthMismatch)?;

    let mut out = Vec::with_capacity(FRAME3D_BINARY_HEADER_LEN + json.len());
    out.extend_from_slice(FRAME3D_BINARY_MAGIC);
    out.push(kind as u8);
    out.extend_from_slice(&len.to_be_bytes());
    out.extend_from_slice(json);
    Ok(out)
}

/// Decode a binary blob produced by [`encode_frame3d_binary`].
pub fn decode_frame3d_binary(bytes: &[u8]) -> Result<Frame3d, Frame3dBinaryError> {
    if bytes.len() < FRAME3D_BINARY_HEADER_LEN {
        return Err(Frame3dBinaryError::TooShort);
    }
    if &bytes[..4] != FRAME3D_BINARY_MAGIC {
        return Err(Frame3dBinaryError::BadMagic);
    }

    let len = u32::from_be_bytes([bytes[5], bytes[6], bytes[7], bytes[8]]) as usize;
    let expected = FRAME3D_BINARY_HEADER_LEN + len;
    if bytes.len() != expected {
        return Err(Frame3dBinaryError::LengthMismatch);
    }

    serde_json::from_slice(&bytes[FRAME3D_BINARY_HEADER_LEN..])
        .map_err(|err| Frame3dBinaryError::InvalidPayload(err.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// FR-CIV-PROTO3D-000 — schema version is exposed.
    #[test]
    fn schema_version_present() {
        assert_eq!(SCHEMA_VERSION, 0);
    }

    /// FR-CIV-PROTO3D-001 — VoxelDeltaFrame round-trips through serde JSON
    /// losslessly. Binary framing lands in a follow-up PR but JSON is a useful
    /// determinism floor.
    #[test]
    fn voxel_delta_frame_roundtrips() {
        let frame = VoxelDeltaFrame {
            tick: 42,
            deltas: vec![VoxelChunkDelta {
                event: DirtyChunkEvent {
                    chunk_id: ChunkId(7),
                    write_seq: WriteSeq(3),
                },
                voxels: vec![MaterialId(0); 16 * 16 * 16],
            }],
        };
        let s = serde_json::to_string(&frame).expect("serialize");
        let back: VoxelDeltaFrame = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(frame, back);
    }

    /// FR-CIV-PROTO3D-002 — building diff carries provenance.
    #[test]
    fn building_diff_carries_provenance() {
        let f = BuildingDiffFrame {
            tick: 100,
            provenance: BuildingProvenance::Freehand,
            buildings: Vec::new(),
        };
        let s = serde_json::to_string(&f).expect("serialize");
        let back: BuildingDiffFrame = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(back.provenance, BuildingProvenance::Freehand);
    }

    /// FR-CIV-PROTO3D-008 — building diff entries and agent positions round-trip.
    #[test]
    fn building_and_agent_position_extensions_roundtrip() {
        let building = BuildingDiffFrame {
            tick: 9,
            provenance: BuildingProvenance::Procedural,
            buildings: vec![BuildingDiffEntry {
                id: 42,
                kind: BuildingKind3d::House,
                position: WorldXZ { x: 12.5, z: 48.0 },
            }],
        };
        let building_json = serde_json::to_string(&building).expect("serialize building");
        let building_back: BuildingDiffFrame =
            serde_json::from_str(&building_json).expect("deserialize building");
        assert_eq!(building, building_back);

        let agent = AgentAppearanceUpdate {
            agent_id: 7,
            era: 1,
            wardrobe: MaterialId(0),
            tools: MaterialId(0),
            scale: 1.0,
            position: Some(WorldXZ { x: 3.0, z: 9.0 }),
        };
        let agent_json = serde_json::to_string(&agent).expect("serialize agent");
        let agent_back: AgentAppearanceUpdate =
            serde_json::from_str(&agent_json).expect("deserialize agent");
        assert_eq!(agent_back.position, Some(WorldXZ { x: 3.0, z: 9.0 }));
        assert_eq!(agent_world_translation(&agent_back, 0.8), (3.0, 0.8, 9.0));
    }

    /// FR-CIV-PROTO3D-003 — Frame3d::tick exposes the inner tick.
    #[test]
    fn frame3d_tick_extraction() {
        let f = Frame3d::VoxelDelta(VoxelDeltaFrame {
            tick: 17,
            deltas: Vec::new(),
        });
        assert_eq!(f.tick(), 17);
    }

    /// FR-CIV-PROTO3D-004 — BuildingDiff round-trips through the binary envelope.
    #[test]
    fn building_diff_binary_roundtrip() {
        let frame = Frame3d::BuildingDiff(BuildingDiffFrame {
            tick: 42,
            provenance: BuildingProvenance::Procedural,
            buildings: Vec::new(),
        });
        let bytes = encode_frame3d_binary(&frame).expect("encode");
        assert!(bytes.starts_with(FRAME3D_BINARY_MAGIC));
        assert_eq!(bytes[4], Frame3dKind::BuildingDiff as u8);
        let back = decode_frame3d_binary(&bytes).expect("decode");
        assert_eq!(back, frame);
    }

    /// FR-CIV-PROTO3D-006 — pre-serialized JSON matches full encode path.
    #[test]
    fn binary_from_json_matches_full_encode() {
        let frame = Frame3d::AgentAppearance(AgentAppearanceFrame {
            tick: 7,
            updates: Vec::new(),
        });
        let json = serde_json::to_vec(&frame).expect("json");
        let from_json = encode_frame3d_binary_from_json(&frame, &json).expect("from json");
        let full = encode_frame3d_binary(&frame).expect("full");
        assert_eq!(from_json, full);
    }

    /// FR-CIV-PROTO3D-007 — agent appearance accepts optional scale with default.
    #[test]
    fn agent_appearance_update_default_scale() {
        let json = r#"{"agent_id":3,"era":1,"wardrobe":0,"tools":0}"#;
        let update: AgentAppearanceUpdate = serde_json::from_str(json).expect("deserialize");
        assert_eq!(update.scale, 1.0);
        let with_scale = r#"{"agent_id":3,"era":1,"wardrobe":0,"tools":0,"scale":1.25}"#;
        let scaled: AgentAppearanceUpdate = serde_json::from_str(with_scale).expect("deserialize");
        assert!((scaled.scale - 1.25).abs() < f32::EPSILON);
    }

    /// FR-CIV-PROTO3D-005 — corrupt magic is rejected.
    #[test]
    fn decode_rejects_bad_magic() {
        let frame = Frame3d::BuildingDiff(BuildingDiffFrame {
            tick: 1,
            provenance: BuildingProvenance::Freehand,
            buildings: Vec::new(),
        });
        let mut bytes = encode_frame3d_binary(&frame).expect("encode");
        bytes[0] = b'X';
        assert_eq!(
            decode_frame3d_binary(&bytes),
            Err(Frame3dBinaryError::BadMagic)
        );
    }
}
