//! civ-protocol-3d — WebSocket binary protocol extensions for the Civis 3D layer.
//!
//! Extends the existing Civis WebSocket JSON-RPC + binary protocol (ADR-003) with
//! frame types for:
//!
//! - **Voxel deltas** — drained `DirtyChunkEvent` batches plus the chunk content
//!   needed to re-mesh on the client side.
//! - **Building diffs** — `BuildingGraph` mutations tagged with provenance
//!   (procedural vs freehand).
//! - **Agent appearance** — per-civilian wardrobe / tools state updates.
//!
//! This crate ships the wire-format types, a versioning gate, and a minimal
//! length-prefixed binary envelope (`encode_frame3d_binary` / `decode_frame3d_binary`).
//! Full zstd-compressed production framing and WebSocket attach land in
//! `civ-server` once the schema stabilises.
//!
//! **Tick batch coalescing:** the server sends three separate `F3D0` frames per
//! tick (voxel, building, agent) rather than one length-prefixed batch blob.
//! Clients already decode individual frames; merging them would require a new
//! magic/batch envelope and break existing decoders for a small WebSocket
//! framing win (3 headers ≈ 27 bytes vs 1).
//!
//! See `docs/development-guide/fr-3d-additions.md` for `FR-CIV-PROTO3D-*`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use serde::{Deserialize, Serialize};

pub use civ_build::{BuildingGraph, BuildingId, FacadeStyle, Parcel, ParcelKind};
pub use civ_voxel::{ChunkId, DirtyChunkEvent, MaterialId, WriteSeq};

/// Schema version of the public protocol-3d frame types. Bumped on any
/// wire-incompatible change; clients refuse to attach on mismatch.
pub const SCHEMA_VERSION: u32 = 0;

/// Provenance tag carried by every building diff so the renderer can style
/// procedural-grown vs user-freehand structures differently if desired.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BuildingProvenance {
    /// Generated by the autonomous demand-driven allocator.
    Procedural,
    /// Authored by the user in freehand mode.
    Freehand,
}

/// World-space X/Z anchor in Bevy terrain units (fixed-scale coords / [`civ_voxel::FIXED_SCALE`]).
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct WorldXZ {
    /// World X in the same units as the Bevy standalone terrain mesh.
    pub x: f32,
    /// World Z in the same units as the Bevy standalone terrain mesh.
    pub z: f32,
}

impl WorldXZ {
    /// Convert a fixed-point [`WorldCoord`] into Bevy terrain units.
    #[must_use]
    pub fn from_fixed_coord(coord: &civ_voxel::WorldCoord) -> Self {
        let scale = civ_voxel::FIXED_SCALE as f32;
        Self {
            x: coord.x as f32 / scale,
            z: coord.z as f32 / scale,
        }
    }
}

/// Building kind mirrored for wire payloads (matches `civ_engine::BuildingType` labels).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BuildingKind3d {
    /// Farm parcel.
    Farm,
    /// Mine parcel.
    Mine,
    /// Barracks parcel.
    Barracks,
    /// Temple parcel.
    Temple,
    /// Market parcel.
    Market,
    /// House parcel.
    House,
    /// City center parcel.
    CityCenter,
}

/// One building entry carried in a [`BuildingDiffFrame`].
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BuildingDiffEntry {
    /// Stable building entity id from the simulation ECS.
    pub id: u64,
    /// Building classification for client-side styling.
    pub kind: BuildingKind3d,
    /// Building tier or upgrade level. Defaults to `0` for legacy payloads.
    #[serde(default)]
    pub tier: u8,
    /// World-space anchor for the building marker mesh.
    pub position: WorldXZ,
}

/// Building-diff frame. Carries provenance plus optional building snapshots for renderers.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BuildingDiffFrame {
    /// Server tick at which the diff was produced.
    pub tick: u64,
    /// Provenance of every mutation in this frame (mixed-provenance frames
    /// carry the dominant provenance — finer per-mutation tagging lives inside
    /// the `BuildingGraph` payload itself once it lands).
    pub provenance: BuildingProvenance,
    /// Buildings visible this tick (full snapshot; empty on legacy servers).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub buildings: Vec<BuildingDiffEntry>,
    /// Full `BuildingGraph` snapshot for facade/provenance detail (optional).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub graph: Option<BuildingGraph>,
}

/// Snapshot of civilian needs for client-side overlays.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct CivilianNeeds3d {
    /// Food satisfaction, normalized to `0.0..=1.0`.
    #[serde(default)]
    pub food: f32,
    /// Shelter satisfaction, normalized to `0.0..=1.0`.
    #[serde(default)]
    pub shelter: f32,
    /// Safety satisfaction, normalized to `0.0..=1.0`.
    #[serde(default)]
    pub safety: f32,
    /// Social satisfaction, normalized to `0.0..=1.0`.
    #[serde(default)]
    pub social: f32,
    /// Rest satisfaction, normalized to `0.0..=1.0`.
    #[serde(default)]
    pub rest: f32,
}

/// Summary of a civilian genome for deterministic visual tagging.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct GenomeSummary3d {
    /// Human-readable summary string.
    #[serde(default)]
    pub summary: String,
    /// Optional short lineage or haplogroup label.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub lineage: String,
    /// Optional compact trait tags.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub traits: Vec<String>,
}

/// A single civilian state payload for the 3D wire protocol.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CivilianStateEntry {
    /// Stable civilian entity id from the simulation ECS.
    pub id: u64,
    /// Latest needs snapshot.
    #[serde(default)]
    pub needs: CivilianNeeds3d,
    /// Occupation label for UI filtering and badges.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub profession: String,
    /// Genome summary payload. Defaults to an empty summary for legacy JSON.
    #[serde(default, rename = "genome-summary")]
    pub genome_summary: GenomeSummary3d,
    /// Species label used by the deepened sim.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub species: String,
    /// Health snapshot. Defaults to `1.0` for legacy JSON.
    #[serde(default = "default_civilian_health")]
    pub health: f32,
}

fn default_civilian_health() -> f32 {
    1.0
}

/// Batch of civilian state updates for one server tick.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CivilianStateFrame {
    /// Server tick at which the state was produced.
    pub tick: u64,
    /// One entry per civilian whose state changed.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub civilians: Vec<CivilianStateEntry>,
}

/// Treasury snapshot for a faction in the 3D wire protocol.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct FactionTreasury3d {
    /// Treasury balance in simulation currency units.
    #[serde(default)]
    pub amount: f64,
    /// Optional human-readable currency label.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub currency: String,
}

/// Government label carried on faction snapshots.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
pub enum Government3d {
    /// Unknown or legacy payload.
    #[default]
    Unknown,
    /// Monarchy or dynastic rule.
    Monarchy,
    /// Republic or elected civic rule.
    Republic,
    /// Theocracy or priestly rule.
    Theocracy,
    /// Military administration.
    Junta,
    /// Council or committee rule.
    Council,
    /// Corporate or merchant rule.
    Corporate,
}

/// A single faction state payload for the 3D wire protocol.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FactionStateEntry {
    /// Stable faction id from the simulation ECS.
    pub id: u32,
    /// Current era index.
    #[serde(default)]
    pub era: u16,
    /// Government label.
    #[serde(default)]
    pub government: Government3d,
    /// Treasury snapshot.
    #[serde(default)]
    pub treasury: FactionTreasury3d,
}

/// Batch of faction state updates for one server tick.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FactionStateFrame {
    /// Server tick at which the state was produced.
    pub tick: u64,
    /// One entry per faction whose state changed.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub factions: Vec<FactionStateEntry>,
}

/// A birth event in the wire-level event feed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct BirthEvent3d {
    /// Stable entity id for the newborn.
    #[serde(default)]
    pub entity_id: u64,
    /// Owning faction id, if known.
    #[serde(default)]
    pub faction_id: u32,
    /// Species label.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub species: String,
    /// Optional spawn location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position: Option<WorldXZ>,
}

/// A death event in the wire-level event feed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct DeathEvent3d {
    /// Stable entity id for the deceased.
    #[serde(default)]
    pub entity_id: u64,
    /// Owning faction id, if known.
    #[serde(default)]
    pub faction_id: u32,
    /// Optional death location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position: Option<WorldXZ>,
    /// Optional cause or short cause label.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub cause: String,
}

/// A technology event in the wire-level event feed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct TechEvent3d {
    /// Owning faction id, if known.
    #[serde(default)]
    pub faction_id: u32,
    /// Era reached or unlocked.
    #[serde(default)]
    pub era: u16,
    /// Technology label or identifier.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub tech: String,
}

/// A battle event in the wire-level event feed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct BattleEvent3d {
    /// Attacking faction id, if known.
    #[serde(default)]
    pub attacker_faction: u32,
    /// Defending faction id, if known.
    #[serde(default)]
    pub defender_faction: u32,
    /// Short outcome summary.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub outcome: String,
    /// Optional battle location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position: Option<WorldXZ>,
}

/// A disaster event in the wire-level event feed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct DisasterEvent3d {
    /// Disaster kind or label.
    ///
    /// Renamed to `disaster_kind` to avoid clashing with the
    /// `EventFeedMessage3d` tagged-enum tag (`#[serde(tag = "kind")]`); the
    /// serializer would otherwise emit two `kind` fields per disaster
    /// message.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub disaster_kind: String,
    /// Optional disaster severity.
    #[serde(default)]
    pub severity: f32,
    /// Optional disaster location.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position: Option<WorldXZ>,
}

/// One feed event emitted by the deepened sim.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EventFeedMessage3d {
    /// Birth message.
    Birth(BirthEvent3d),
    /// Death message.
    Death(DeathEvent3d),
    /// Technology message.
    Tech(TechEvent3d),
    /// Battle message.
    Battle(BattleEvent3d),
    /// Disaster message.
    Disaster(DisasterEvent3d),
}

/// Batch of event-feed messages for one server tick.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EventFeedFrame {
    /// Server tick at which the events were emitted.
    pub tick: u64,
    /// One feed message per simulation event.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub events: Vec<EventFeedMessage3d>,
}

/// One delta event for a single chunk. The renderer pairs `event` with the
/// `voxels` payload to re-mesh the affected chunk.
///
/// Wire layout: `event` is ~24 bytes (ChunkId u64 + WriteSeq u64 + bounds in a
/// follow-up). `voxels` is the dense leaf payload (`16^3 = 4096` voxels) packed
/// as `MaterialId` u16s = 8 KiB per dirty chunk before zstd. Practical
/// production framing will be either:
///
/// - Delta-encoded RLE over `voxels` for cheap chunks
/// - Whole-chunk replacement for fully-edited chunks
///
/// Both encodings ride on top of this type; the encoding tag lands in the
/// follow-up PR that introduces the wire format.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VoxelChunkDelta {
    /// The drained dirty event that triggered this delta.
    pub event: DirtyChunkEvent,
    /// Full dense-leaf voxel payload for the affected chunk.
    pub voxels: Vec<MaterialId>,
}

/// A batch of voxel deltas delivered after one server tick. The batch is always
/// pre-sorted by `(chunk_id, write_seq)` (the kernel guarantees this via
/// `VoxelWorld::drain_dirty`); clients can rely on iteration order being
/// identical across machines.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct VoxelDeltaFrame {
    /// Server tick at which the batch was produced.
    pub tick: u64,
    /// One entry per affected chunk.
    pub deltas: Vec<VoxelChunkDelta>,
}

/// Agent appearance update — one entry per agent whose visible state changed
/// this tick (wardrobe, tools, era).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentAppearanceFrame {
    /// Server tick at which the update was produced.
    pub tick: u64,
    /// One entry per agent whose appearance changed.
    pub updates: Vec<AgentAppearanceUpdate>,
}

/// A single per-agent appearance state update.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentAppearanceUpdate {
    /// Opaque ECS entity ID. The server side ensures stable IDs across ticks.
    pub agent_id: u64,
    /// Era index — drives the diffusion-curve-driven facade/wardrobe rendering.
    pub era: u16,
    /// Wardrobe material slot.
    pub wardrobe: MaterialId,
    /// Tools material slot.
    pub tools: MaterialId,
    /// Uniform scale multiplier for the agent marker mesh (`1.0` when omitted).
    #[serde(default = "default_agent_scale")]
    pub scale: f32,
    /// World-space anchor when the server knows agent ECS position (item 29+).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position: Option<WorldXZ>,
}

fn default_agent_scale() -> f32 {
    1.0
}

/// Climate broadcast for one tick. Carries the planetary day/year/moon/tide
/// phase plus the per-region weather grid so 3D clients can drive sky,
/// lighting, and ambient effects without re-running the simulation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ClimateFrame {
    /// Server tick at which the climate was sampled.
    pub tick: u64,
    /// Planetary phase snapshot.
    pub climate: civ_planet::Climate,
    /// One weather cell per region, in the same region-id space used by the
    /// `GeologyMap` / `RegionBiome` wire types.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub weather: Vec<civ_planet::WeatherCell>,
}

/// Discriminated union of all 3D-extension protocol frames. The existing Civis
/// protocol carries this inside its binary-frame envelope.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Frame3d {
    /// Voxel-delta batch for one tick.
    VoxelDelta(VoxelDeltaFrame),
    /// Building-diff batch for one tick.
    BuildingDiff(BuildingDiffFrame),
    /// Agent appearance batch for one tick.
    AgentAppearance(AgentAppearanceFrame),
    /// Civilian state batch for one tick.
    CivilianState(CivilianStateFrame),
    /// Faction state batch for one tick.
    FactionState(FactionStateFrame),
    /// Event-feed batch for one tick.
    EventFeed(EventFeedFrame),
    /// Climate broadcast for one tick (planetary phase + per-region weather).
    /// Distinct from the other batch frames because it ticks on its own cadence
    /// (driven by the planet sim) and carries a different per-tick payload shape.
    Climate(ClimateFrame),
}

impl Frame3d {
    /// Server tick this frame was produced at.
    #[must_use]
    pub fn tick(&self) -> u64 {
        match self {
            Self::VoxelDelta(f) => f.tick,
            Self::BuildingDiff(f) => f.tick,
            Self::AgentAppearance(f) => f.tick,
            Self::CivilianState(f) => f.tick,
            Self::FactionState(f) => f.tick,
            Self::EventFeed(f) => f.tick,
            Self::Climate(f) => f.tick,
        }
    }
}

/// Resolve agent world translation for 3D clients (legacy fallback uses `agent_id` on X).
#[must_use]
pub fn agent_world_translation(update: &AgentAppearanceUpdate, y: f32) -> (f32, f32, f32) {
    if let Some(pos) = update.position {
        (pos.x, y, pos.z)
    } else {
        (update.agent_id as f32, y, 0.0)
    }
}

/// Maps civ-build provenance tags into wire [`BuildingProvenance`].
#[must_use]
pub fn map_build_provenance(provenance: civ_build::BuildingProvenance) -> BuildingProvenance {
    match provenance {
        civ_build::BuildingProvenance::Procedural => BuildingProvenance::Procedural,
        civ_build::BuildingProvenance::Freehand => BuildingProvenance::Freehand,
    }
}

/// 4-byte magic identifying civ-protocol-3d binary frames (CIV-0200 partial).
pub const FRAME3D_BINARY_MAGIC: &[u8; 4] = b"F3D0";

/// Header size: magic (4) + kind tag (1) + payload length (4, big-endian).
const FRAME3D_BINARY_HEADER_LEN: usize = 9;

/// Variant tag carried in the binary header (kind byte).
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Frame3dKind {
    VoxelDelta = 0,
    BuildingDiff = 1,
    AgentAppearance = 2,
    CivilianState = 3,
    FactionState = 4,
    EventFeed = 5,
    Climate = 6,
}

impl Frame3dKind {
    fn from_frame(frame: &Frame3d) -> Self {
        match frame {
            Frame3d::VoxelDelta(_) => Self::VoxelDelta,
            Frame3d::BuildingDiff(_) => Self::BuildingDiff,
            Frame3d::AgentAppearance(_) => Self::AgentAppearance,
            Frame3d::CivilianState(_) => Self::CivilianState,
            Frame3d::FactionState(_) => Self::FactionState,
            Frame3d::EventFeed(_) => Self::EventFeed,
            Frame3d::Climate(_) => Self::Climate,
        }
    }
}

/// Errors from binary frame encode/decode.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Frame3dBinaryError {
    /// Magic bytes do not match [`FRAME3D_BINARY_MAGIC`].
    BadMagic,
    /// Buffer is shorter than the fixed header.
    TooShort,
    /// Declared payload length does not match the buffer.
    LengthMismatch,
    /// JSON payload could not be serialized or parsed.
    InvalidPayload(String),
}

/// Encode a [`Frame3d`] as `magic || kind || len_be || json`.
///
/// JSON carries the full tagged union so clients can reuse existing serde
/// schemas while the binary envelope satisfies CIV-0200 binary-frame clients.
pub fn encode_frame3d_binary(frame: &Frame3d) -> Result<Vec<u8>, Frame3dBinaryError> {
    let json = serde_json::to_vec(frame)
        .map_err(|err| Frame3dBinaryError::InvalidPayload(err.to_string()))?;
    encode_frame3d_binary_from_json(frame, &json)
}

/// Wrap already-serialized JSON bytes in the `F3D0` envelope for `frame`.
///
/// Use when the same JSON is sent as a WebSocket text frame and as the binary
/// payload (avoids a second `serde_json` pass in `Both` tick-broadcast mode).
pub fn encode_frame3d_binary_from_json(
    frame: &Frame3d,
    json: &[u8],
) -> Result<Vec<u8>, Frame3dBinaryError> {
    let kind = Frame3dKind::from_frame(frame);
    let len = u32::try_from(json.len()).map_err(|_| Frame3dBinaryError::LengthMismatch)?;

    let mut out = Vec::with_capacity(FRAME3D_BINARY_HEADER_LEN + json.len());
    out.extend_from_slice(FRAME3D_BINARY_MAGIC);
    out.push(kind as u8);
    out.extend_from_slice(&len.to_be_bytes());
    out.extend_from_slice(json);
    Ok(out)
}

/// Decode a binary blob produced by [`encode_frame3d_binary`].
pub fn decode_frame3d_binary(bytes: &[u8]) -> Result<Frame3d, Frame3dBinaryError> {
    if bytes.len() < FRAME3D_BINARY_HEADER_LEN {
        return Err(Frame3dBinaryError::TooShort);
    }
    if &bytes[..4] != FRAME3D_BINARY_MAGIC {
        return Err(Frame3dBinaryError::BadMagic);
    }

    let len = u32::from_be_bytes([bytes[5], bytes[6], bytes[7], bytes[8]]) as usize;
    let expected = FRAME3D_BINARY_HEADER_LEN + len;
    if bytes.len() != expected {
        return Err(Frame3dBinaryError::LengthMismatch);
    }

    serde_json::from_slice(&bytes[FRAME3D_BINARY_HEADER_LEN..])
        .map_err(|err| Frame3dBinaryError::InvalidPayload(err.to_string()))
}

/// Returns `true` if `bytes` starts with [`FRAME3D_BINARY_MAGIC`].
pub fn is_frame3d_binary(bytes: &[u8]) -> bool {
    bytes.len() >= FRAME3D_BINARY_MAGIC.len()
        && &bytes[..FRAME3D_BINARY_MAGIC.len()] == FRAME3D_BINARY_MAGIC
}

// ===================================================================
// Agents stream — efficient per-agent id + position for thousands of
// agents. See FR-CIV-PROTO3D-014..017.
// ===================================================================

/// Grid step in meters used by the agents-stream quantization. 0.25 m (25 cm)
/// is finer than typical civilian leg-length (~0.8 m) and gives ±8.19 km of
/// positional reach from the stream origin in each axis before an i16 cell
/// would overflow.
///
/// Rationale: at 0.25 m the per-cell error is at most `GRID_STEP_M / 2 = 0.125 m`,
/// which is below the per-frame visible jitter of a walking civilian mesh
/// (the human eye cannot reliably detect sub-decimeter offsets at the camera
/// distances used by the 3D clients). Doubling the resolution to 0.125 m would
/// halve the range; halving it to 0.5 m would push the visible jitter close to
/// the leg-length boundary.
pub const GRID_STEP_M: f32 = 0.25;

/// 4-byte magic for the parallel `AgentStream` envelope. Distinct from
/// `FRAME3D_BINARY_MAGIC` so legacy decoders that do not understand it can
/// skip the frame on magic mismatch (the Civis WebSocket binary dispatcher
/// already drops unknown magics as a no-op).
pub const AGENT_STREAM_MAGIC: &[u8; 4] = b"F3AS";

/// Current wire-version of the `AgentStream` envelope. Bumped on any
/// wire-incompatible change. Decoders must reject frames whose version
/// exceeds their highest supported version.
pub const AGENT_STREAM_VERSION: u8 = 1;

/// Capability / mode flag bits carried in the `AgentStream` header.
///
/// Bit 0 — [`AgentStreamMode::Full`]: each entry is a fresh id + absolute
/// quantized cell from the stream origin. Cheap to encode/decode, tolerant
/// of dropped frames (client just refills on the next full snapshot). This
/// is the default mode the server ships while agent counts are in the
/// hundreds.
///
/// Bit 1 — [`AgentStreamMode::Delta`]: each entry carries an id + a signed
/// cell delta from the previous tick. Implemented as a future optimization
/// once the scale law actually pushes agent counts into the thousands (see
/// the PR alternatives discussion for the threshold rationale).
///
/// Bits 2..7 — reserved, must be zero on the wire; decoders ignore them.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct AgentStreamFlags(pub u8);

impl AgentStreamFlags {
    /// Build a `FullSnapshot` flag byte (bit 0 set).
    #[must_use]
    pub const fn full_snapshot() -> Self {
        Self(0b0000_0001)
    }

    /// Build a `DeltaSnapshot` flag byte (bit 1 set).
    #[must_use]
    pub const fn delta_snapshot() -> Self {
        Self(0b0000_0010)
    }

    /// Returns the wire-level mode.
    #[must_use]
    pub const fn mode(self) -> AgentStreamMode {
        match self.0 & 0b0000_0011 {
            0b01 => AgentStreamMode::Full,
            0b10 => AgentStreamMode::Delta,
            // Reserved / unknown bits fall back to FullSnapshot so old
            // clients that have never seen a mode byte still get a useful
            // frame.
            _ => AgentStreamMode::Full,
        }
    }
}

/// Stream-mode selector derived from the flag bits.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AgentStreamMode {
    /// Each entry is a full id + absolute quantized cell.
    Full,
    /// Each entry is id + signed delta cell from the previous tick.
    /// Reserved for the follow-up delta PR; the v1 envelope accepts the
    /// flag bit but rejects the payload with [`AgentStreamBinaryError::UnsupportedMode`].
    Delta,
}

/// Header for the parallel `AgentStream` envelope.
///
/// Wire layout (big-endian):
///
/// ```text
///   0..4   magic        "F3AS"
///   4      version      u8   (must equal AGENT_STREAM_VERSION)
///   5      flags        u8   (see [`AgentStreamFlags`])
///   6..10  agent_count  u32
///   10..18 tick         u64
///   18..22 origin_x     i32  (cell count offset for absolute coords)
///   22..26 origin_y     i32
///   26..30 origin_z     i32
/// ```
///
/// `agent_count * 10` entry bytes follow. In `FullSnapshot` mode each entry
/// is `{ id: u32, cell_x: i16, cell_y: i16, cell_z: i16 }`. In `DeltaSnapshot`
/// mode the same layout is reused for `{ id: u32, dcell_x: i16, dcell_y: i16, dcell_z: i16 }`
/// (signed deltas).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentStreamHeader {
    /// Server tick at which the snapshot was produced.
    pub tick: u64,
    /// Number of [`AgentStreamEntry`] records that follow.
    pub agent_count: u32,
    /// Mode / capability flags.
    pub flags: AgentStreamFlags,
    /// Cell-grid origin used to bias absolute cell coordinates (see
    /// [`encode_agent_stream_binary`]). Stored as raw i32 cell counts so
    /// the origin is itself a 25 cm-aligned cell index.
    pub origin: GridOriginI32,
}

/// Three-axis cell-grid origin stored as raw i32 cell counts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct GridOriginI32 {
    /// X origin (cells).
    pub x: i32,
    /// Y origin (cells).
    pub y: i32,
    /// Z origin (cells).
    pub z: i32,
}

/// One agent entry inside an `AgentStream` envelope.
///
/// In `Full` mode the cell components are the absolute position
/// `(agent_world - origin) / GRID_STEP_M`, signed i16, and the renderer
/// reverses the transform. In `Delta` mode they are signed i16 deltas
/// from the previous tick (reserved — see [`AgentStreamMode::Delta`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentStreamEntry {
    /// Stable entity id from the simulation ECS. u32 keeps the entry at
    /// 10 bytes; Civis civilian ids fit comfortably under 2^32 across
    /// the foreseeable scale law.
    pub id: u32,
    /// Quantized cell X (absolute in `Full` mode, delta in `Delta` mode).
    pub cell_x: i16,
    /// Quantized cell Y.
    pub cell_y: i16,
    /// Quantized cell Z.
    pub cell_z: i16,
}

/// Decoded `AgentStream` payload as returned to clients.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentStream {
    /// Parsed header.
    pub header: AgentStreamHeader,
    /// Per-agent entries (length always equals `header.agent_count`).
    pub entries: Vec<AgentStreamEntry>,
}

const AGENT_STREAM_HEADER_LEN: usize = 30;
const AGENT_STREAM_ENTRY_LEN: usize = 10;
const AGENT_STREAM_MAX_AGENTS: u32 = 65_536;

/// Errors raised by `AgentStream` binary encode / decode.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AgentStreamBinaryError {
    /// Magic bytes do not match [`AGENT_STREAM_MAGIC`].
    BadMagic,
    /// Buffer is shorter than the fixed header.
    TooShort,
    /// Header version is not supported by this decoder.
    UnsupportedVersion(u8),
    /// Mode flag is reserved (delta is accepted by the flag parser but
    /// the v1 decoder refuses the payload).
    UnsupportedMode(AgentStreamMode),
    /// Declared agent count would not fit the buffer.
    LengthMismatch {
        /// Expected byte length.
        expected: usize,
        /// Actual byte length.
        actual: usize,
    },
    /// A cell coordinate would not round-trip through the i16 grid given
    /// the configured origin + step.
    CellOutOfRange {
        /// Agent id whose cell overflowed.
        agent_id: u32,
        /// Axis (`0` = X, `1` = Y, `2` = Z).
        axis: u8,
    },
}

/// Quantize a world-space meter offset into a signed i16 cell index
/// relative to a cell-grid origin.
///
/// Returns `None` when the world offset cannot be expressed in i16 cells
/// at the current `GRID_STEP_M`. Callers should treat that as a
/// `CellOutOfRange` encode error.
#[must_use]
pub fn quantize_axis(world_m: f32, origin_cells: i32) -> Option<i16> {
    let cells = (world_m / GRID_STEP_M).round() + origin_cells as f32;
    if !cells.is_finite() {
        return None;
    }
    // Saturate instead of overflowing on the encode side so a single bad
    // agent cannot abort the whole stream — but we still want the encoder
    // to flag it for diagnostics.
    if cells > i16::MAX as f32 || cells < i16::MIN as f32 {
        return None;
    }
    Some(cells as i16)
}

/// Dequantize a signed i16 cell index back to a world-space meter offset.
#[must_use]
pub fn dequantize_axis(cell: i16, origin_cells: i32) -> f32 {
    (cell as i32 - origin_cells) as f32 * GRID_STEP_M
}

/// Encode an `AgentStream` to its wire bytes (`F3AS || version || flags || ...`).
///
/// Quantization is bounded by `i16::MIN..=i16::MAX` cells (≈ ±8.19 km per
/// axis at the default `GRID_STEP_M`). Callers needing a wider envelope
/// should re-center the `origin` (the server can split a single tick
/// across multiple streams for a continent-scale world).
pub fn encode_agent_stream_binary(stream: &AgentStream) -> Result<Vec<u8>, AgentStreamBinaryError> {
    if stream.entries.len() as u64 != u64::from(stream.header.agent_count) {
        return Err(AgentStreamBinaryError::LengthMismatch {
            expected: stream.header.agent_count as usize * AGENT_STREAM_ENTRY_LEN,
            actual: stream.entries.len() * AGENT_STREAM_ENTRY_LEN,
        });
    }
    if stream.header.agent_count > AGENT_STREAM_MAX_AGENTS {
        return Err(AgentStreamBinaryError::LengthMismatch {
            expected: AGENT_STREAM_MAX_AGENTS as usize * AGENT_STREAM_ENTRY_LEN,
            actual: stream.entries.len() * AGENT_STREAM_ENTRY_LEN,
        });
    }
    // Per-entry cells are i16 by construction (see [`AgentStreamEntry`]);
    // the encoder cannot produce an out-of-range value. Callers converting
    // world-meters to cells should use [`quantize_axis`] so they get a
    // `None` before passing a stale number into the stream.

    let total = AGENT_STREAM_HEADER_LEN + stream.entries.len() * AGENT_STREAM_ENTRY_LEN;
    let mut out = Vec::with_capacity(total);
    out.extend_from_slice(AGENT_STREAM_MAGIC);
    out.push(AGENT_STREAM_VERSION);
    out.push(stream.header.flags.0);
    out.extend_from_slice(&stream.header.agent_count.to_be_bytes());
    out.extend_from_slice(&stream.header.tick.to_be_bytes());
    out.extend_from_slice(&stream.header.origin.x.to_be_bytes());
    out.extend_from_slice(&stream.header.origin.y.to_be_bytes());
    out.extend_from_slice(&stream.header.origin.z.to_be_bytes());

    for entry in &stream.entries {
        out.extend_from_slice(&entry.id.to_be_bytes());
        out.extend_from_slice(&entry.cell_x.to_be_bytes());
        out.extend_from_slice(&entry.cell_y.to_be_bytes());
        out.extend_from_slice(&entry.cell_z.to_be_bytes());
    }
    debug_assert_eq!(out.len(), total);
    Ok(out)
}

/// Decode an `AgentStream` envelope previously produced by
/// [`encode_agent_stream_binary`].
pub fn decode_agent_stream_binary(bytes: &[u8]) -> Result<AgentStream, AgentStreamBinaryError> {
    if bytes.len() < AGENT_STREAM_HEADER_LEN {
        return Err(AgentStreamBinaryError::TooShort);
    }
    if &bytes[..4] != AGENT_STREAM_MAGIC {
        return Err(AgentStreamBinaryError::BadMagic);
    }
    let version = bytes[4];
    if version != AGENT_STREAM_VERSION {
        return Err(AgentStreamBinaryError::UnsupportedVersion(version));
    }
    let flags = AgentStreamFlags(bytes[5]);
    let mode = flags.mode();
    if mode == AgentStreamMode::Delta {
        return Err(AgentStreamBinaryError::UnsupportedMode(mode));
    }
    let agent_count = u32::from_be_bytes([bytes[6], bytes[7], bytes[8], bytes[9]]);
    let expected = AGENT_STREAM_HEADER_LEN
        .checked_add(agent_count as usize * AGENT_STREAM_ENTRY_LEN)
        .ok_or(AgentStreamBinaryError::LengthMismatch {
            expected: 0,
            actual: bytes.len(),
        })?;
    if bytes.len() != expected {
        return Err(AgentStreamBinaryError::LengthMismatch {
            expected,
            actual: bytes.len(),
        });
    }

    let tick = u64::from_be_bytes([
        bytes[10], bytes[11], bytes[12], bytes[13], bytes[14], bytes[15], bytes[16], bytes[17],
    ]);
    let origin = GridOriginI32 {
        x: i32::from_be_bytes([bytes[18], bytes[19], bytes[20], bytes[21]]),
        y: i32::from_be_bytes([bytes[22], bytes[23], bytes[24], bytes[25]]),
        z: i32::from_be_bytes([bytes[26], bytes[27], bytes[28], bytes[29]]),
    };

    let header = AgentStreamHeader {
        tick,
        agent_count,
        flags,
        origin,
    };

    let mut entries = Vec::with_capacity(agent_count as usize);
    let mut cursor = AGENT_STREAM_HEADER_LEN;
    for _ in 0..agent_count {
        let id = u32::from_be_bytes([
            bytes[cursor],
            bytes[cursor + 1],
            bytes[cursor + 2],
            bytes[cursor + 3],
        ]);
        let cell_x = i16::from_be_bytes([bytes[cursor + 4], bytes[cursor + 5]]);
        let cell_y = i16::from_be_bytes([bytes[cursor + 6], bytes[cursor + 7]]);
        let cell_z = i16::from_be_bytes([bytes[cursor + 8], bytes[cursor + 9]]);
        entries.push(AgentStreamEntry {
            id,
            cell_x,
            cell_y,
            cell_z,
        });
        cursor += AGENT_STREAM_ENTRY_LEN;
    }

    Ok(AgentStream { header, entries })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn map_build_provenance_preserves_variant() {
        assert_eq!(
            map_build_provenance(civ_build::BuildingProvenance::Procedural),
            BuildingProvenance::Procedural
        );
        assert_eq!(
            map_build_provenance(civ_build::BuildingProvenance::Freehand),
            BuildingProvenance::Freehand
        );
    }

    #[test]
    fn world_xz_from_fixed_coord_projects_and_preserves_sign() {
        // Fixed-point WorldCoord -> Bevy world XZ: divide by FIXED_SCALE,
        // drop Y, and preserve sign (scale is a positive constant).
        let xz = WorldXZ::from_fixed_coord(&civ_voxel::WorldCoord {
            x: 1_000_000,
            y: 7,
            z: -1_000_000,
        });
        assert!(xz.x > 0.0, "positive fixed x maps to positive world x");
        assert!(xz.z < 0.0, "negative fixed z maps to negative world z");

        let origin = WorldXZ::from_fixed_coord(&civ_voxel::WorldCoord { x: 0, y: 0, z: 0 });
        assert_eq!(origin.x, 0.0);
        assert_eq!(origin.z, 0.0);
    }

    /// Covers FR-CIV-PROTO3D-000 — schema version is exposed.
    #[test]
    fn fr_civ_proto3d_000_schema_version_present() {
        assert_eq!(SCHEMA_VERSION, 0);
    }

    /// Covers FR-CIV-PROTO3D-001 — VoxelDeltaFrame round-trips through serde JSON
    /// losslessly. Binary framing lands in a follow-up PR but JSON is a useful
    /// determinism floor.
    #[test]
    fn fr_civ_proto3d_001_voxel_delta_frame_roundtrips() {
        let frame = VoxelDeltaFrame {
            tick: 42,
            deltas: vec![VoxelChunkDelta {
                event: DirtyChunkEvent {
                    chunk_id: ChunkId(7),
                    write_seq: WriteSeq(3),
                },
                voxels: vec![MaterialId(0); 16 * 16 * 16],
            }],
        };
        let s = serde_json::to_string(&frame).expect("serialize");
        let back: VoxelDeltaFrame = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(frame, back);
    }

    /// Covers FR-CIV-PROTO3D-002 — building diff carries provenance.
    #[test]
    fn fr_civ_proto3d_002_building_diff_carries_provenance() {
        let f = BuildingDiffFrame {
            tick: 100,
            provenance: BuildingProvenance::Freehand,
            buildings: Vec::new(),
            graph: None,
        };
        let s = serde_json::to_string(&f).expect("serialize");
        let back: BuildingDiffFrame = serde_json::from_str(&s).expect("deserialize");
        assert_eq!(back.provenance, BuildingProvenance::Freehand);
    }

    /// Covers FR-CIV-PROTO3D-010 — building tier defaults for legacy payloads and round-trips when present.
    #[test]
    fn fr_civ_proto3d_010_building_diff_entry_tier_roundtrip_and_backward_compat() {
        let entry = BuildingDiffEntry {
            id: 99,
            kind: BuildingKind3d::Market,
            tier: 3,
            position: WorldXZ { x: 1.5, z: 2.5 },
        };
        let json = serde_json::to_string(&entry).expect("serialize");
        let back: BuildingDiffEntry = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, entry);

        let legacy_json = r#"{"id":99,"kind":"Market","position":{"x":1.5,"z":2.5}}"#;
        let legacy: BuildingDiffEntry =
            serde_json::from_str(legacy_json).expect("legacy deserialize");
        assert_eq!(legacy.tier, 0);
    }

    /// Covers FR-CIV-PROTO3D-009 — optional `BuildingGraph` snapshot round-trips on building diff frames.
    #[test]
    fn fr_civ_proto3d_009_building_graph_snapshot_roundtrips() {
        use civ_build::{BuildingId, BuildingProvenance as BuildProvenance, ParcelKind};

        let mut graph = BuildingGraph::new();
        graph.insert_parcel(Parcel {
            id: BuildingId(7),
            kind: ParcelKind::Residential,
            origin: civ_voxel::WorldCoord {
                x: 128,
                y: 0,
                z: 256,
            },
            size: [8, 6, 4],
            era_min: 1,
        });
        graph.set_provenance(BuildingId(7), BuildProvenance::Freehand);

        let frame = BuildingDiffFrame {
            tick: 12,
            provenance: BuildingProvenance::Freehand,
            buildings: Vec::new(),
            graph: Some(graph.clone()),
        };
        let json = serde_json::to_string(&frame).expect("serialize");
        let back: BuildingDiffFrame = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back.graph, Some(graph));
    }

    /// Covers FR-CIV-PROTO3D-008 — building diff entries and agent positions round-trip.
    #[test]
    fn fr_civ_proto3d_008_building_and_agent_position_extensions_roundtrip() {
        let building = BuildingDiffFrame {
            tick: 9,
            provenance: BuildingProvenance::Procedural,
            buildings: vec![BuildingDiffEntry {
                id: 42,
                kind: BuildingKind3d::House,
                tier: 1,
                position: WorldXZ { x: 12.5, z: 48.0 },
            }],
            graph: None,
        };
        let building_json = serde_json::to_string(&building).expect("serialize building");
        let building_back: BuildingDiffFrame =
            serde_json::from_str(&building_json).expect("deserialize building");
        assert_eq!(building, building_back);

        let agent = AgentAppearanceUpdate {
            agent_id: 7,
            era: 1,
            wardrobe: MaterialId(0),
            tools: MaterialId(0),
            scale: 1.0,
            position: Some(WorldXZ { x: 3.0, z: 9.0 }),
        };
        let agent_json = serde_json::to_string(&agent).expect("serialize agent");
        let agent_back: AgentAppearanceUpdate =
            serde_json::from_str(&agent_json).expect("deserialize agent");
        assert_eq!(agent_back.position, Some(WorldXZ { x: 3.0, z: 9.0 }));
        assert_eq!(agent_world_translation(&agent_back, 0.8), (3.0, 0.8, 9.0));
    }

    /// Covers FR-CIV-PROTO3D-011 — civilian state entries round-trip and legacy payloads get defaults.
    #[test]
    fn fr_civ_proto3d_011_civilian_state_entry_roundtrip_and_backward_compat() {
        let entry = CivilianStateEntry {
            id: 17,
            needs: CivilianNeeds3d {
                food: 0.8,
                shelter: 0.6,
                safety: 0.7,
                social: 0.5,
                rest: 0.9,
            },
            profession: "farmer".to_string(),
            genome_summary: GenomeSummary3d {
                summary: "dominant traits".to_string(),
                lineage: "line-a".to_string(),
                traits: vec!["hardy".to_string(), "curious".to_string()],
            },
            species: "human".to_string(),
            health: 0.95,
        };
        let json = serde_json::to_string(&entry).expect("serialize");
        let back: CivilianStateEntry = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, entry);

        let legacy_json = r#"{"id":17}"#;
        let legacy: CivilianStateEntry =
            serde_json::from_str(legacy_json).expect("legacy deserialize");
        assert_eq!(legacy.needs, CivilianNeeds3d::default());
        assert_eq!(legacy.profession, "");
        assert_eq!(legacy.genome_summary, GenomeSummary3d::default());
        assert_eq!(legacy.species, "");
        assert_eq!(legacy.health, 1.0);
    }

    /// Covers FR-CIV-PROTO3D-012 — faction state entries round-trip and legacy payloads get defaults.
    #[test]
    fn fr_civ_proto3d_012_faction_state_entry_roundtrip_and_backward_compat() {
        let entry = FactionStateEntry {
            id: 4,
            era: 9,
            government: Government3d::Republic,
            treasury: FactionTreasury3d {
                amount: 1234.5,
                currency: "civ".to_string(),
            },
        };
        let json = serde_json::to_string(&entry).expect("serialize");
        let back: FactionStateEntry = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, entry);

        let legacy_json = r#"{"id":4}"#;
        let legacy: FactionStateEntry =
            serde_json::from_str(legacy_json).expect("legacy deserialize");
        assert_eq!(legacy.era, 0);
        assert_eq!(legacy.government, Government3d::Unknown);
        assert_eq!(legacy.treasury, FactionTreasury3d::default());
    }

    /// Covers FR-CIV-PROTO3D-013 — event feed messages round-trip as a tagged enum.
    #[test]
    fn fr_civ_proto3d_013_event_feed_roundtrip() {
        let frame = EventFeedFrame {
            tick: 27,
            events: vec![
                EventFeedMessage3d::Birth(BirthEvent3d {
                    entity_id: 1,
                    faction_id: 2,
                    species: "human".to_string(),
                    position: Some(WorldXZ { x: 10.0, z: 12.0 }),
                }),
                EventFeedMessage3d::Death(DeathEvent3d {
                    entity_id: 3,
                    faction_id: 4,
                    position: Some(WorldXZ { x: 8.0, z: 9.0 }),
                    cause: "battle".to_string(),
                }),
                EventFeedMessage3d::Tech(TechEvent3d {
                    faction_id: 5,
                    era: 6,
                    tech: "agriculture".to_string(),
                }),
                EventFeedMessage3d::Battle(BattleEvent3d {
                    attacker_faction: 7,
                    defender_faction: 8,
                    outcome: "attacker_won".to_string(),
                    position: Some(WorldXZ { x: 1.0, z: 2.0 }),
                }),
                EventFeedMessage3d::Disaster(DisasterEvent3d {
                    disaster_kind: "flood".to_string(),
                    severity: 0.75,
                    position: Some(WorldXZ { x: 3.0, z: 4.0 }),
                }),
            ],
        };
        let json = serde_json::to_string(&frame).expect("serialize");
        let back: EventFeedFrame = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(back, frame);
    }

    /// Covers FR-CIV-PROTO3D-003 — Frame3d::tick exposes the inner tick.
    #[test]
    fn fr_civ_proto3d_003_frame3d_tick_extraction() {
        let f = Frame3d::VoxelDelta(VoxelDeltaFrame {
            tick: 17,
            deltas: Vec::new(),
        });
        assert_eq!(f.tick(), 17);

        let faction = Frame3d::FactionState(FactionStateFrame {
            tick: 21,
            factions: Vec::new(),
        });
        assert_eq!(faction.tick(), 21);
    }

    /// Covers FR-CIV-PROTO3D-004 — BuildingDiff round-trips through the binary envelope.
    #[test]
    fn fr_civ_proto3d_004_building_diff_binary_roundtrip() {
        let frame = Frame3d::BuildingDiff(BuildingDiffFrame {
            tick: 42,
            provenance: BuildingProvenance::Procedural,
            buildings: Vec::new(),
            graph: None,
        });
        let bytes = encode_frame3d_binary(&frame).expect("encode");
        assert!(bytes.starts_with(FRAME3D_BINARY_MAGIC));
        assert_eq!(bytes[4], Frame3dKind::BuildingDiff as u8);
        let back = decode_frame3d_binary(&bytes).expect("decode");
        assert_eq!(back, frame);
    }

    /// Covers FR-CIV-PROTO3D-006 — pre-serialized JSON matches full encode path.
    #[test]
    fn binary_from_json_matches_full_encode() {
        let frame = Frame3d::AgentAppearance(AgentAppearanceFrame {
            tick: 7,
            updates: Vec::new(),
        });
        let json = serde_json::to_vec(&frame).expect("json");
        let from_json = encode_frame3d_binary_from_json(&frame, &json).expect("from json");
        let full = encode_frame3d_binary(&frame).expect("full");
        assert_eq!(from_json, full);

        let event_frame = Frame3d::EventFeed(EventFeedFrame {
            tick: 8,
            events: vec![EventFeedMessage3d::Tech(TechEvent3d {
                faction_id: 1,
                era: 2,
                tech: "printing".to_string(),
            })],
        });
        let event_bytes = encode_frame3d_binary(&event_frame).expect("full event");
        assert_eq!(event_bytes[4], Frame3dKind::EventFeed as u8);
        assert_eq!(
            decode_frame3d_binary(&event_bytes).expect("decode event"),
            event_frame
        );
    }

    /// Covers FR-CIV-PROTO3D-007 — agent appearance accepts optional scale with default.
    #[test]
    fn agent_appearance_update_default_scale() {
        let json = r#"{"agent_id":3,"era":1,"wardrobe":0,"tools":0}"#;
        let update: AgentAppearanceUpdate = serde_json::from_str(json).expect("deserialize");
        assert_eq!(update.scale, 1.0);
        let with_scale = r#"{"agent_id":3,"era":1,"wardrobe":0,"tools":0,"scale":1.25}"#;
        let scaled: AgentAppearanceUpdate = serde_json::from_str(with_scale).expect("deserialize");
        assert!((scaled.scale - 1.25).abs() < f32::EPSILON);
    }

    /// Covers FR-CIV-PROTO3D-005 — corrupt magic is rejected.
    #[test]
    fn decode_rejects_bad_magic() {
        let frame = Frame3d::BuildingDiff(BuildingDiffFrame {
            tick: 1,
            provenance: BuildingProvenance::Freehand,
            buildings: Vec::new(),
            graph: None,
        });
        let mut bytes = encode_frame3d_binary(&frame).expect("encode");
        bytes[0] = b'X';
        assert_eq!(
            decode_frame3d_binary(&bytes),
            Err(Frame3dBinaryError::BadMagic)
        );
    }

    #[test]
    fn frame3d_binary_round_trips() {
        let frame = Frame3d::VoxelDelta(VoxelDeltaFrame {
            tick: 42,
            deltas: vec![VoxelChunkDelta {
                event: DirtyChunkEvent {
                    chunk_id: ChunkId(7),
                    write_seq: WriteSeq(3),
                },
                voxels: vec![MaterialId(0); 16 * 16 * 16],
            }],
        });
        let bytes = encode_frame3d_binary(&frame).expect("encode");
        assert!(is_frame3d_binary(&bytes));
        let decoded = decode_frame3d_binary(&bytes).expect("decode");
        assert_eq!(decoded, frame);
    }

    #[test]
    fn is_frame3d_binary_rejects_non_envelope() {
        assert!(!is_frame3d_binary(b"nope"));
        assert!(!is_frame3d_binary(&[]));
        assert!(!is_frame3d_binary(b"xx"));
    }

    #[test]
    fn decode_frame3d_binary_rejects_short_and_bad_magic() {
        assert!(matches!(
            decode_frame3d_binary(&[0u8; 2]),
            Err(Frame3dBinaryError::TooShort)
        ));
        let buf = vec![0u8; FRAME3D_BINARY_HEADER_LEN + 4];
        assert!(matches!(
            decode_frame3d_binary(&buf),
            Err(Frame3dBinaryError::BadMagic)
        ));
    }

    // -----------------------------------------------------------
    // FR-CIV-PROTO3D-014..017 — AgentStream parallel envelope.
    // -----------------------------------------------------------

    /// Covers FR-CIV-PROTO3D-014 — the parallel `AgentStream` envelope encodes a
    /// header + zero or more `{id, cell_x, cell_y, cell_z}` entries and the
    /// decoder returns the same payload (identity round-trip).
    #[test]
    fn agent_stream_roundtrip_identity() {
        let origin = GridOriginI32 { x: 0, y: 0, z: 0 };
        let stream = AgentStream {
            header: AgentStreamHeader {
                tick: 1_234_567,
                agent_count: 4,
                flags: AgentStreamFlags::full_snapshot(),
                origin,
            },
            entries: vec![
                AgentStreamEntry {
                    id: 1,
                    cell_x: 0,
                    cell_y: 0,
                    cell_z: 0,
                },
                AgentStreamEntry {
                    id: 7,
                    cell_x: 4,
                    cell_y: 8,
                    cell_z: -4,
                },
                AgentStreamEntry {
                    id: 12,
                    cell_x: -100,
                    cell_y: 200,
                    cell_z: i16::MAX,
                },
                AgentStreamEntry {
                    id: u32::MAX,
                    cell_x: i16::MIN,
                    cell_y: i16::MIN,
                    cell_z: i16::MAX,
                },
            ],
        };
        let bytes = encode_agent_stream_binary(&stream).expect("encode");
        // Header is fixed at 30 bytes + N * 10 entries.
        assert_eq!(
            bytes.len(),
            AGENT_STREAM_HEADER_LEN + stream.entries.len() * AGENT_STREAM_ENTRY_LEN
        );
        assert!(bytes.starts_with(AGENT_STREAM_MAGIC));
        let back = decode_agent_stream_binary(&bytes).expect("decode");
        assert_eq!(back, stream);
    }

    /// Covers FR-CIV-PROTO3D-014 (roundtrip property) — for arbitrary agent sets
    /// satisfying the i16 cell bound, encode -> decode is the identity.
    /// Manual property loop (mirrors what `proptest!` would do); keeps the
    /// test self-contained so it runs in this PR even on crates that have
    /// not enabled `proptest` features.
    #[test]
    fn agent_stream_roundtrip_property() {
        let cases: Vec<(u32, Vec<AgentStreamEntry>)> = vec![
            (0, vec![]),
            (
                1,
                vec![AgentStreamEntry {
                    id: 0,
                    cell_x: 0,
                    cell_y: 0,
                    cell_z: 0,
                }],
            ),
            (
                3,
                (0..3)
                    .map(|i| AgentStreamEntry {
                        id: i,
                        cell_x: (i as i16).wrapping_mul(17),
                        cell_y: (i as i16).wrapping_mul(-23),
                        cell_z: (i as i16).wrapping_mul(101),
                    })
                    .collect(),
            ),
            (
                256,
                (0..256u32)
                    .map(|i| AgentStreamEntry {
                        id: i.wrapping_mul(7919),
                        cell_x: (i as i16).wrapping_mul(31),
                        cell_y: (i as i16).wrapping_mul(-41),
                        cell_z: (i as i16).wrapping_mul(53),
                    })
                    .collect(),
            ),
        ];
        for (tick_mod, entries) in cases {
            let stream = AgentStream {
                header: AgentStreamHeader {
                    tick: u64::from(tick_mod) * 1_000,
                    agent_count: entries.len() as u32,
                    flags: AgentStreamFlags::full_snapshot(),
                    origin: GridOriginI32 { x: 0, y: 0, z: 0 },
                },
                entries,
            };
            let bytes = encode_agent_stream_binary(&stream).expect("encode");
            let back = decode_agent_stream_binary(&bytes).expect("decode");
            assert_eq!(back, stream, "roundtrip mismatch for tick_mod={tick_mod}");
        }
    }

    /// Covers FR-CIV-PROTO3D-015 — quantization is bounded by `GRID_STEP_M / 2`
    /// per axis for every world-meter offset that fits in the i16 grid.
    /// Tests the chosen step (0.25 m) against the documented bound.
    #[test]
    fn agent_stream_quantization_error_bound() {
        // Sweep across the i16 cell range and assert |round(w) - w| <= step/2.
        let bounds_check = |world_m: f32| {
            let cell = quantize_axis(world_m, 0).expect("in range");
            let recovered = dequantize_axis(cell, 0);
            let err = (recovered - world_m).abs();
            assert!(
                err <= GRID_STEP_M / 2.0 + 1e-5,
                "world={world_m} cell={cell} recovered={recovered} err={err} > step/2"
            );
        };
        for raw in -3_000..=3_000 {
            let w = (raw as f32) * 0.137_f32; // arbitrary non-grid values
            bounds_check(w);
        }
    }

    /// Covers FR-CIV-PROTO3D-015 — `quantize_axis` rejects values that would
    /// overflow the i16 grid (i.e. the world origin is mis-configured).
    #[test]
    fn agent_stream_quantization_out_of_range() {
        // 1_000_000 m at 0.25 m step -> 4_000_000 cells -> overflows i16.
        assert_eq!(quantize_axis(1_000_000.0, 0), None);
        // Negative extreme likewise.
        assert_eq!(quantize_axis(-1_000_000.0, 0), None);
        // Non-finite world offsets are rejected.
        assert_eq!(quantize_axis(f32::NAN, 0), None);
        assert_eq!(quantize_axis(f32::INFINITY, 0), None);
        // Within-range values still succeed at the i16 boundary.
        assert!(quantize_axis(0.0, 0).is_some());
        // Just inside the i16 boundary (~+8191.75 m at 0.25 m step) succeeds.
        assert!(quantize_axis(8_000.0, 0).is_some());
        // Just outside fails.
        assert_eq!(quantize_axis(10_000.0, 0), None);
    }

    /// Covers FR-CIV-PROTO3D-016 — capability / mode flag is parsed and the delta
    /// mode is reserved (rejected at decode time so old clients fail fast
    /// instead of silently corrupting positions).
    #[test]
    fn agent_stream_capability_flag_modes() {
        assert_eq!(
            AgentStreamFlags::full_snapshot().mode(),
            AgentStreamMode::Full
        );
        assert_eq!(
            AgentStreamFlags::delta_snapshot().mode(),
            AgentStreamMode::Delta
        );
        // Reserved / unknown flag bits fall back to Full (defensive default).
        let unknown = AgentStreamFlags(0b1000_0000);
        assert_eq!(unknown.mode(), AgentStreamMode::Full);
    }

    /// Covers FR-CIV-PROTO3D-016 — a `Delta` frame on the wire is rejected by the
    /// v1 decoder with `UnsupportedMode` (older clients are not expected to
    /// understand the format).
    #[test]
    fn agent_stream_decode_rejects_delta_mode() {
        let mut bytes = AGENT_STREAM_MAGIC.to_vec();
        bytes.push(AGENT_STREAM_VERSION);
        bytes.push(AgentStreamFlags::delta_snapshot().0);
        bytes.extend_from_slice(&0u32.to_be_bytes()); // agent_count = 0
        bytes.extend_from_slice(&0u64.to_be_bytes());
        bytes.extend_from_slice(&[0u8; 12]); // origin
        assert_eq!(
            decode_agent_stream_binary(&bytes),
            Err(AgentStreamBinaryError::UnsupportedMode(
                AgentStreamMode::Delta
            ))
        );
    }

    /// Covers FR-CIV-PROTO3D-017 — corrupt magic / short buffer / length mismatch /
    /// unknown version all produce distinct errors so the dispatcher can
    /// route them.
    #[test]
    fn agent_stream_decode_rejects_bad_inputs() {
        // Bad magic.
        let mut bad_magic = vec![b'X', b'X', b'X', b'X'];
        bad_magic.extend_from_slice(&[AGENT_STREAM_VERSION, AgentStreamFlags::full_snapshot().0]);
        bad_magic.extend_from_slice(&0u32.to_be_bytes());
        bad_magic.extend_from_slice(&0u64.to_be_bytes());
        bad_magic.extend_from_slice(&[0u8; 12]);
        assert_eq!(
            decode_agent_stream_binary(&bad_magic),
            Err(AgentStreamBinaryError::BadMagic)
        );

        // Too short.
        assert_eq!(
            decode_agent_stream_binary(&[0u8; 5]),
            Err(AgentStreamBinaryError::TooShort)
        );

        // Unknown version.
        let mut unknown = AGENT_STREAM_MAGIC.to_vec();
        unknown.push(99);
        unknown.push(AgentStreamFlags::full_snapshot().0);
        unknown.extend_from_slice(&0u32.to_be_bytes());
        unknown.extend_from_slice(&0u64.to_be_bytes());
        unknown.extend_from_slice(&[0u8; 12]);
        assert_eq!(
            decode_agent_stream_binary(&unknown),
            Err(AgentStreamBinaryError::UnsupportedVersion(99))
        );

        // Length mismatch: header promises 5 entries but only the header follows.
        let mut mismatch = AGENT_STREAM_MAGIC.to_vec();
        mismatch.push(AGENT_STREAM_VERSION);
        mismatch.push(AgentStreamFlags::full_snapshot().0);
        mismatch.extend_from_slice(&5u32.to_be_bytes());
        mismatch.extend_from_slice(&0u64.to_be_bytes());
        mismatch.extend_from_slice(&[0u8; 12]);
        assert_eq!(
            decode_agent_stream_binary(&mismatch),
            Err(AgentStreamBinaryError::LengthMismatch {
                expected: AGENT_STREAM_HEADER_LEN + 5 * AGENT_STREAM_ENTRY_LEN,
                actual: mismatch.len(),
            })
        );
    }

    /// Covers FR-CIV-PROTO3D-014 — agent count > MAX is rejected at encode time
    /// (the v1 stream caps at 65 536 entries to keep header math bounded).
    #[test]
    fn agent_stream_encode_rejects_overflow() {
        let entries = (0..AGENT_STREAM_MAX_AGENTS + 1)
            .map(|i| AgentStreamEntry {
                id: i,
                cell_x: 0,
                cell_y: 0,
                cell_z: 0,
            })
            .collect();
        let stream = AgentStream {
            header: AgentStreamHeader {
                tick: 0,
                agent_count: AGENT_STREAM_MAX_AGENTS + 1,
                flags: AgentStreamFlags::full_snapshot(),
                origin: GridOriginI32::default(),
            },
            entries,
        };
        let err = encode_agent_stream_binary(&stream).expect_err("overflow rejected");
        assert!(matches!(err, AgentStreamBinaryError::LengthMismatch { .. }));
    }

    /// Covers FR-CIV-PROTO3D — epic: all Frame3d variants losslessly round-trip F3D0 binary envelope.
    #[test]
    fn fr_civ_proto3d_epic_all_frame3d_variants_f3d0_roundtrip() {
        const TICK: u64 = 99;
        let frames: [(u8, Frame3d); 7] = [
            (
                Frame3dKind::VoxelDelta as u8,
                Frame3d::VoxelDelta(VoxelDeltaFrame {
                    tick: TICK,
                    deltas: vec![],
                }),
            ),
            (
                Frame3dKind::BuildingDiff as u8,
                Frame3d::BuildingDiff(BuildingDiffFrame {
                    tick: TICK,
                    provenance: BuildingProvenance::Procedural,
                    buildings: vec![],
                    graph: None,
                }),
            ),
            (
                Frame3dKind::AgentAppearance as u8,
                Frame3d::AgentAppearance(AgentAppearanceFrame {
                    tick: TICK,
                    updates: vec![],
                }),
            ),
            (
                Frame3dKind::CivilianState as u8,
                Frame3d::CivilianState(CivilianStateFrame {
                    tick: TICK,
                    civilians: vec![],
                }),
            ),
            (
                Frame3dKind::FactionState as u8,
                Frame3d::FactionState(FactionStateFrame {
                    tick: TICK,
                    factions: vec![],
                }),
            ),
            (
                Frame3dKind::EventFeed as u8,
                Frame3d::EventFeed(EventFeedFrame {
                    tick: TICK,
                    events: vec![],
                }),
            ),
            (
                Frame3dKind::Climate as u8,
                Frame3d::Climate(ClimateFrame {
                    tick: TICK,
                    climate: civ_planet::Climate::default(),
                    weather: vec![],
                }),
            ),
        ];

        for (expected_kind, frame) in frames {
            assert_eq!(frame.tick(), TICK);
            let bytes = encode_frame3d_binary(&frame).expect("encode");
            assert!(is_frame3d_binary(&bytes));
            assert_eq!(&bytes[0..4], FRAME3D_BINARY_MAGIC);
            assert_eq!(bytes[4], expected_kind);
            let back = decode_frame3d_binary(&bytes).expect("decode");
            assert_eq!(back, frame);
        }

        assert_eq!(
            map_build_provenance(civ_build::BuildingProvenance::Procedural),
            BuildingProvenance::Procedural
        );
    }
}
