@echo off
for %%b in (
  backup/frecon005-20260614
  chore/bevy-omniroute-parallel
  chore/dependabot-frontend-2026-06-05
  chore/parallel-session-sync
  chore/tech-debt-sweep
  civis-pbr
  docs/branch-recovery-worklist
  docs/p-p1-kickoff
  docs/phantom-id-triage-2
  docs/phantom-id-triage-3
  docs/sync-status-2026-05-28
  feat/astar-obstacle-pathfinding
  feat/build-next-13
  feat/build-next-7
  feat/civ003-lifecycle
  feat/civ007-diplomacy
  feat/civis-bevy-game
  feat/civis-life-sim
  feat/civis-pbr2-triplanar
  feat/civis-theme-fix
  feat/civis-wave1-emergence
  feat/emergence-live-wiring
  feat/emergence-onto-main
  feat/frecon005-allocation
  feat/p-l1-kickoff
  feat/p-p1-fr040-geology
  feat/p-w1-bevy-gameplay-026
  feat/p-w1-bevy-item-027
  feat/p-w1-civsave-zst
  feat/p-w1-float-flow
  feat/p-w1-mod-install
  feat/p-w1-tactics-002-los
  feat/p-w1-tactics-009
  feat/p-w1-tactics-010
  feat/p-w1-tactics-011
  feat/process-compose
  feat/session-persistence
  feat/tactics-ui
  feat/war-bridge-los-formation
  fix/clippy-warnings
  fix/governance-gate-cache-bypass
  fix/justfile-check
  fix/launch-asset-sync
  fix/pr-333-review
  fix/tactics-fog-of-war-wire-in
  fix/terrain-fragmentation
  merge-333-arena
  side/perf-probe
  test/fr-batch11
  test/fr-linkage-3
  wip/asset-audit
  wip/civ003-design
  wip/civ007-design
  wip/econ-tiering-pending-verify
  wip/gfx-settings
  wip/native-ocean
  wip/terrain-apron
  wip/ui-holocron-theme
  wt/actor-y-fix
  wt/capability-enforce
  wt/chunk-seam
  wt/emergence-spawn
  wt/map-seed
  wt/map2d-ux-2494
  wt/map2d-zoom
  wt/mod-hot-reload
  wt/mod-publish-store
  wt/policy-mod-sdk
  wt/remote-mod-store
  wt/rust-mod-verify
  wt/rust-tests
  wt/save-session-db
  wt/save-slot-rpc
  wt/session-saved-bus
  wt/tools-wire
  wt/ui-design
  wt/water-placement
  wt/web-remote-mod-ui
  wt/web-save-slot-rpc
) do (
  echo ===BRANCH:%%b===
  git log --format="" --name-only -5 "%%b" 2^>nul | sort /unique
  echo.
)
