"""Verdicts for the multi-id tag blocks that the triage reports never reached.

These are hand-audited. Each id was traced from the requirement sentence to the
symbol that actually performs the behavior, and the verdict records where that
symbol is (or that none exists). The three reports dispatched for this audit
covered engine/core/social, sim/domain, and asset/RTS; the crates below fell
between those lanes, so nothing had ruled on them.
"""
import pathlib
import re
import sys

REPO = pathlib.Path(r"C:\Users\koosh\Civis-clone")
ID_RE = re.compile(r"\b(?:FR|NFR)-[A-Z0-9]+(?:-[A-Z0-9]+)*\b")

SITES = [
    (
        "crates/build/src/lib.rs",
        "SCHEMA_VERSION",
        {
            "FR-API-002": (
                "NOT IMPLEMENTED, and the id is not a property of this constant. The "
                "requirement is a Python scenario runner: civlab.run_scenario(path, "
                "ticks=50) must complete a 50-tick run in under 5 s, civlab must be "
                "pip-installable with all dependencies declared, and every public API "
                "method must carry type annotations and docstrings "
                "(agileplus-specs/civ-013-research-api/spec.md:26). There is no civlab "
                "package in this repository: no civlab directory, no pyproject.toml or "
                "setup.py at the root, and no .py file mentioning civlab outside "
                "docs/. The tagged declaration is a Rust &str literal "
                "pub const SCHEMA_VERSION: &str = \"0.1.0-stub\". A version string "
                "cannot install a package or run a scenario. Real implementing symbol: "
                "none."
            ),
            "FR-API-003": (
                "NOT IMPLEMENTED, and the id is not a property of this constant. The "
                "requirement is a policy-parameter override: a dict passed to "
                "run_scenario must merge with scenario defaults, invalid parameter names "
                "must raise ValueError listing the allowed parameters, and values must be "
                "validated against type constraints before the simulation starts "
                "(civ-013 spec.md:27). This is Python-side behavior in a package that "
                "does not exist. The constant names a version and merges nothing."
            ),
            "FR-API-004": (
                "NOT IMPLEMENTED, and the id is not a property of this constant. The "
                "requirement is data export: civlab.export(run_id, format=\"csv\") must "
                "write a per-tick metric table, JSON export must include the full event "
                "log, and export must complete in under 30 s for a 100,000-tick run "
                "(civ-013 spec.md:28). No such function exists in any language in this "
                "repository. All three ids were stacked on one line above the constant, "
                "which made a single Rust string look like a spec with three "
                "discharged parts."
            ),
        },
        [
            "Three ids on one line above a version constant. All three are unchecked",
            "acceptance boxes in civ-013 and all three are Python-package requirements,",
            "sitting on a Rust string. They were plausibly auto-generated by matching the",
            "constant's name to the spec's 'schema' wording, which is the failure mode this",
            "whole audit exists to remove.",
        ],
    ),
    (
        "crates/economy/src/lib.rs",
        "SCHEMA_VERSION",
        {
            "FR-CIV-ECON-001-MARKET": (
                "MIS-BOUND. The economy ledger serialization requirement is discharged "
                "by the ledger types themselves (LedgerEntry and friends in this crate) "
                "plus the save/load path, not by a version string. The constant is a "
                "version marker for wire compatibility, which is at most adjacent to the "
                "requirement rather than an implementation of it. Kept here only until "
                "the real artifact is located; the binding as written is not defensible."
            ),
            "FR-CIV-MARKET-001": (
                "MIS-BOUND. Same finding as the id above it. The market-state "
                "requirement is about the market data model and its behavior, which "
                "lives in crates/economy/src/market.rs. A bare version string is not the "
                "market."
            ),
        },
        [
            "Two economy ids stacked on a version constant, same shape as the build/src",
            "case. These are recorded as mis-bound rather than false, because the",
            "requirements themselves are real and the ledger and market types in this",
            "crate plausibly discharge them; only the binding is wrong. That is a weaker",
            "finding than the build/src ones and is flagged for a follow-up pass that",
            "locates the true artifacts rather than being removed outright here.",
        ],
    ),
]

if __name__ == "__main__":
    # Self-check: every id must actually be tagged on the named declaration today.
    bad = 0
    for rel, decl, removed, _note in SITES:
        path = REPO / rel
        lines = path.read_text(encoding="utf-8").split("\n")
        idx = next(
            (
                i
                for i, l in enumerate(lines)
                if re.match(
                    r"pub(?:\([^)]*\))?\s+(?:struct|enum|const|static|type)\s+"
                    + re.escape(decl)
                    + r"\b",
                    l.strip(),
                )
            ),
            None,
        )
        if idx is None:
            print(f"FAIL: {rel} :: {decl} not found")
            bad += 1
            continue
        block = "\n".join(lines[max(0, idx - 12) : idx])
        found = set(ID_RE.findall(block))
        for ident in removed:
            mark = "ok " if ident in found else "MISSING"
            if ident not in found:
                bad += 1
            print(f"  {mark} {rel} :: {decl} {ident}")
    print("\nRESULT:", "PASS" if bad == 0 else f"FAIL ({bad} problem(s))")
    sys.exit(1 if bad else 0)
