"""Append the batch rows generated by generate-batch-rows.py into
the main fr-emergence-matrix.md as Section B. Idempotent.
"""
import sys, pathlib

repo = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.')
main_path  = repo / 'docs' / 'traceability' / 'fr-emergence-matrix.md'
batch_path = repo / 'docs' / 'traceability' / 'fr-emergence-batches.md'

main  = main_path.read_text(encoding='utf-8')
batch = batch_path.read_text(encoding='utf-8')

# Detect Section B already appended
if 'Section B: Emergence batch rows' in main:
    print('ALREADY_APPENDED — skipping')
    sys.exit(0)

# Strip the preamble from the batch file (just keep the table)
# The batch file starts with '# FR Emergence Batches' as the first line.
batch_table_start = batch.find('| FR ID |')
if batch_table_start < 0:
    print('ERR: batch file has no table')
    sys.exit(1)

batch_table = batch[batch_table_start:]

# Append as Section B
separator = '\n\n---\n\n## Section B: Emergence batch rows (§3.1 + §3.2, all currently dormant)\n\n'
out = main.rstrip() + separator + batch_table + '\n'
main_path.write_text(out, encoding='utf-8')

row_count = out.count('| FR ID |')
total_kb  = len(out) // 1024
print(f'appended OK  rows_in_main={row_count}  total_size_kb={total_kb}')