//! Shadow economy simulation layer for the Civis godgame.
//!
//! Simulates underground markets, contraband trade, corruption dynamics, and
//! law-enforcement detection mechanics across settlements.

use std::collections::HashMap;

use rand::Rng;
use serde::{Deserialize, Serialize};

/// Types of goods traded in the shadow economy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ShadowGood {
    /// Illegal or regulated substances.
    Contraband,
    /// Goods smuggled across borders to evade tariffs.
    SmuggledGoods,
    /// Fake goods sold as genuine.
    Counterfeit,
    /// Looted or embezzled items.
    StolenGoods,
    /// Prohibited substances.
    BannedSubstances,
}

impl ShadowGood {
    /// Base risk factor for each good type (0.0 – 1.0).
    pub fn risk_factor(&self) -> f32 {
        match self {
            ShadowGood::Contraband => 0.8,
            ShadowGood::SmuggledGoods => 0.4,
            ShadowGood::Counterfeit => 0.3,
            ShadowGood::StolenGoods => 0.7,
            ShadowGood::BannedSubstances => 0.9,
        }
    }

    /// Iterate over all variants.
    pub fn all() -> &'static [ShadowGood] {
        &[
            ShadowGood::Contraband,
            ShadowGood::SmuggledGoods,
            ShadowGood::Counterfeit,
            ShadowGood::StolenGoods,
            ShadowGood::BannedSubstances,
        ]
    }
}

/// A listing for a good on a shadow market.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShadowListing {
    /// The type of good.
    pub good: ShadowGood,
    /// Price per unit.
    pub price: f32,
    /// Available quantity.
    pub quantity: u32,
    /// Originating settlement ID.
    pub origin: u32,
}

/// A record of a shadow transaction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShadowTransaction {
    /// Source settlement ID.
    pub from_settlement: u32,
    /// Destination settlement ID.
    pub to_settlement: u32,
    /// Type of good traded.
    pub good: ShadowGood,
    /// Amount traded.
    pub quantity: u32,
    /// Total price.
    pub price: f32,
    /// Whether the transaction was detected by law enforcement.
    pub detected: bool,
}

/// A regional shadow market.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShadowMarket {
    /// Active listings in this market.
    pub goods: Vec<ShadowListing>,
    /// Local corruption level (0.0 – 1.0).
    pub corruption_level: f32,
    /// Strength of local law enforcement (0.0 – 1.0).
    pub law_enforcement_strength: f32,
}

/// Aggregated effects of the shadow economy on the state.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CorruptionEffects {
    /// Labor diverted from the formal economy.
    pub labor_loss: f32,
    /// Taxes evaded through shadow trade.
    pub tax_evasion: f32,
    /// Decay in institutional trust.
    pub trust_decay: f32,
    /// GDP generated by the black market.
    pub black_market_gdp: f32,
}

/// Context for a settlement's shadow economy evaluation.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SettlementShadowState {
    /// Settlement ID.
    pub settlement_id: u32,
    /// Basic prosperity index.
    pub prosperity: f32,
    /// Unemployment rate.
    pub unemployment: f32,
}

/// The core engine driving the shadow economy simulation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShadowEconomyEngine {
    /// Regional markets keyed by settlement ID.
    pub markets: HashMap<u32, ShadowMarket>,
    /// Accumulated corruption over time.
    pub corruption_accumulator: f32,
    /// Log of all executed transactions.
    pub transactions_log: Vec<ShadowTransaction>,
}

impl ShadowEconomyEngine {
    /// Create a new, empty shadow economy engine.
    pub fn new() -> Self {
        Self {
            markets: HashMap::new(),
            corruption_accumulator: 0.0,
            transactions_log: Vec::new(),
        }
    }

    /// Evaluate potential shadow listings for a settlement based on its state
    /// and the given corruption level.
    ///
    /// High unemployment and high corruption increase the likelihood and
    /// volume of shadow goods appearing on the market.
    pub fn evaluate(
        &self,
        settlement_state: &SettlementShadowState,
        corruption: f32,
    ) -> Vec<ShadowListing> {
        let mut listings = Vec::new();
        let mut rng = rand::thread_rng();

        // Shadow economy thrives on high unemployment and corruption
        let base_demand = settlement_state.unemployment * corruption;

        if base_demand > 0.1 {
            for &good in ShadowGood::all() {
                // ~25 % chance each good type appears
                if rng.gen_ratio(1, 4) {
                    let price_base = good.risk_factor() * 100.0;
                    let price = price_base * (1.0 + corruption);
                    let quantity = (base_demand * 100.0) as u32;

                    listings.push(ShadowListing {
                        good,
                        price,
                        quantity,
                        origin: settlement_state.settlement_id,
                    });
                }
            }
        }

        listings
    }

    /// Execute a shadow transaction. Returns the transaction with the
    /// `detected` flag set according to law-enforcement and good-risk
    /// probability.
    pub fn execute_transaction(
        &mut self,
        mut tx: ShadowTransaction,
        rng: &mut impl Rng,
    ) -> ShadowTransaction {
        let market = self.markets.get(&tx.from_settlement);
        let enforcement = market.map_or(0.5, |m| m.law_enforcement_strength);
        let good_risk = tx.good.risk_factor();

        let detection_chance = enforcement * good_risk;
        tx.detected = rng.gen::<f32>() < detection_chance;

        self.transactions_log.push(tx.clone());
        self.corruption_accumulator += 0.01;

        tx
    }

    /// Advance the shadow economy by `dt` time units.
    ///
    /// Markets grow when corruption exceeds law enforcement and shrink
    /// otherwise. The corruption accumulator decays slowly over time.
    pub fn tick(&mut self, dt: f32) {
        for market in self.markets.values_mut() {
            // Corruption drives market expansion
            let growth = (market.corruption_level - market.law_enforcement_strength) * dt * 0.1;

            for listing in &mut market.goods {
                let quantity_change = (growth * listing.quantity as f32) as i32;
                listing.quantity = listing.quantity.saturating_add_signed(quantity_change);

                // Price fluctuation
                listing.price *= 1.0 + (growth * 0.05);
            }

            // Grow / shrink corruption level
            market.corruption_level = (market.corruption_level + growth * 0.001).clamp(0.0, 1.0);
        }

        // Decay accumulator slightly over time
        self.corruption_accumulator = (self.corruption_accumulator - dt * 0.005).max(0.0);
    }

    /// Calculate total shadow GDP across all markets.
    pub fn total_shadow_gdp(&self) -> f32 {
        self.markets
            .values()
            .flat_map(|m| &m.goods)
            .map(|l| l.price * l.quantity as f32)
            .sum()
    }

    /// Calculate the aggregate corruption effects on the formal economy.
    pub fn corruption_impact(&self) -> CorruptionEffects {
        let black_market_gdp = self.total_shadow_gdp();
        let total_corruption = self.corruption_accumulator;

        CorruptionEffects {
            labor_loss: total_corruption * 0.4,
            tax_evasion: black_market_gdp * 0.2,
            trust_decay: total_corruption * 0.1,
            black_market_gdp,
        }
    }
}

impl Default for ShadowEconomyEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ─── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use rand::SeedableRng;

    // 1 ─ Market creation
    #[test]
    fn new_engine_has_no_markets() {
        let engine = ShadowEconomyEngine::new();
        assert!(engine.markets.is_empty());
        assert_eq!(engine.corruption_accumulator, 0.0);
        assert!(engine.transactions_log.is_empty());
    }

    // 2 ─ Evaluate produces listings under high corruption / unemployment
    #[test]
    fn evaluate_produces_listings_when_conditions_favorable() {
        let engine = ShadowEconomyEngine::new();
        let state = SettlementShadowState {
            settlement_id: 1,
            prosperity: 0.5,
            unemployment: 0.8,
        };

        // Run many times to account for randomness
        let mut found = false;
        for _ in 0..50 {
            let listings = engine.evaluate(&state, 0.6);
            if !listings.is_empty() {
                found = true;
                for l in &listings {
                    assert_eq!(l.origin, 1);
                    assert!(l.price > 0.0);
                }
                break;
            }
        }
        assert!(
            found,
            "evaluate should eventually produce listings for high unemployment + corruption"
        );
    }

    // 3 ─ Evaluate returns nothing when corruption is low
    #[test]
    fn evaluate_returns_nothing_when_corruption_low() {
        let engine = ShadowEconomyEngine::new();
        let state = SettlementShadowState {
            settlement_id: 1,
            prosperity: 0.9,
            unemployment: 0.1,
        };

        let listings = engine.evaluate(&state, 0.05);
        assert!(listings.is_empty());
    }

    // 4 ─ Execute transaction records and accumulates corruption
    #[test]
    fn execute_transaction_records_and_accumulates_corruption() {
        let mut engine = ShadowEconomyEngine::new();
        let mut rng = rand::rngs::StdRng::seed_from_u64(42);

        let tx = ShadowTransaction {
            from_settlement: 1,
            to_settlement: 2,
            good: ShadowGood::Contraband,
            quantity: 10,
            price: 100.0,
            detected: false,
        };

        let result = engine.execute_transaction(tx, &mut rng);
        assert_eq!(engine.transactions_log.len(), 1);
        assert!(engine.corruption_accumulator > 0.0);
        assert_eq!(result.from_settlement, 1);
        assert_eq!(result.to_settlement, 2);
    }

    // 5 ─ Detection probability scales with enforcement
    #[test]
    fn detection_increases_with_enforcement() {
        // With max enforcement and high-risk good, every tx should be detected
        let mut engine_strict = ShadowEconomyEngine::new();
        engine_strict.markets.insert(
            1,
            ShadowMarket {
                goods: vec![],
                corruption_level: 0.8,
                law_enforcement_strength: 1.0,
            },
        );

        let mut engine_lenient = ShadowEconomyEngine::new();
        engine_lenient.markets.insert(
            2,
            ShadowMarket {
                goods: vec![],
                corruption_level: 0.8,
                law_enforcement_strength: 0.0,
            },
        );

        let mut detected_strict = 0u32;
        let mut detected_lenient = 0u32;
        let runs = 200;

        for i in 0..runs {
            let mut rng_s = rand::rngs::StdRng::seed_from_u64(i);
            let mut rng_l = rand::rngs::StdRng::seed_from_u64(i);

            let tx_s = ShadowTransaction {
                from_settlement: 1,
                to_settlement: 2,
                good: ShadowGood::BannedSubstances,
                quantity: 5,
                price: 50.0,
                detected: false,
            };
            let tx_l = ShadowTransaction {
                from_settlement: 2,
                to_settlement: 3,
                good: ShadowGood::BannedSubstances,
                quantity: 5,
                price: 50.0,
                detected: false,
            };

            if engine_strict.execute_transaction(tx_s, &mut rng_s).detected {
                detected_strict += 1;
            }
            if engine_lenient
                .execute_transaction(tx_l, &mut rng_l)
                .detected
            {
                detected_lenient += 1;
            }
        }

        assert!(
            detected_strict > detected_lenient,
            "enforcement=1.0 detected {detected_strict} vs enforcement=0.0 detected {detected_lenient}"
        );
    }

    // 6 ─ Tick grows market when corruption > enforcement
    #[test]
    fn tick_grows_market_when_corruption_high() {
        let mut engine = ShadowEconomyEngine::new();
        engine.markets.insert(
            1,
            ShadowMarket {
                goods: vec![ShadowListing {
                    good: ShadowGood::SmuggledGoods,
                    price: 50.0,
                    quantity: 100,
                    origin: 1,
                }],
                corruption_level: 0.7,
                law_enforcement_strength: 0.2,
            },
        );

        engine.tick(10.0);
        let market = engine.markets.get(&1).unwrap();
        assert!(
            market.goods[0].quantity >= 100,
            "quantity should grow when corruption >> enforcement"
        );
    }

    // 7 ─ Tick shrinks market when enforcement > corruption
    #[test]
    fn tick_shrinks_market_when_enforcement_high() {
        let mut engine = ShadowEconomyEngine::new();
        engine.markets.insert(
            1,
            ShadowMarket {
                goods: vec![ShadowListing {
                    good: ShadowGood::SmuggledGoods,
                    price: 50.0,
                    quantity: 1000,
                    origin: 1,
                }],
                corruption_level: 0.2,
                law_enforcement_strength: 0.9,
            },
        );

        engine.tick(10.0);
        let market = engine.markets.get(&1).unwrap();
        assert!(
            market.goods[0].quantity < 1000,
            "quantity should shrink when enforcement >> corruption"
        );
    }

    // 8 ─ total_shadow_gdp sums across markets
    #[test]
    fn total_shadow_gdp_sums_across_markets() {
        let mut engine = ShadowEconomyEngine::new();
        engine.markets.insert(
            1,
            ShadowMarket {
                goods: vec![ShadowListing {
                    good: ShadowGood::Counterfeit,
                    price: 10.0,
                    quantity: 50,
                    origin: 1,
                }],
                corruption_level: 0.5,
                law_enforcement_strength: 0.3,
            },
        );
        engine.markets.insert(
            2,
            ShadowMarket {
                goods: vec![ShadowListing {
                    good: ShadowGood::StolenGoods,
                    price: 20.0,
                    quantity: 30,
                    origin: 2,
                }],
                corruption_level: 0.6,
                law_enforcement_strength: 0.1,
            },
        );

        // 10*50 + 20*30 = 500 + 600 = 1100
        assert_eq!(engine.total_shadow_gdp(), 1100.0);
    }

    // 9 ─ corruption_impact derives correct effects
    #[test]
    fn corruption_impact_derives_correct_effects() {
        let mut engine = ShadowEconomyEngine::new();
        engine.corruption_accumulator = 10.0;
        engine.markets.insert(
            1,
            ShadowMarket {
                goods: vec![ShadowListing {
                    good: ShadowGood::StolenGoods,
                    price: 20.0,
                    quantity: 10,
                    origin: 1,
                }],
                corruption_level: 0.5,
                law_enforcement_strength: 0.2,
            },
        );

        let impact = engine.corruption_impact();
        // black_market_gdp = 20 * 10 = 200
        assert_eq!(impact.black_market_gdp, 200.0);
        assert!((impact.tax_evasion - 40.0).abs() < 0.01); // 200 * 0.2
        assert!((impact.labor_loss - 4.0).abs() < 0.01); // 10 * 0.4
        assert!((impact.trust_decay - 1.0).abs() < 0.01); // 10 * 0.1
    }

    // 10 ─ corruption accumulator decays on tick
    #[test]
    fn tick_decays_corruption_accumulator() {
        let mut engine = ShadowEconomyEngine::new();
        engine.corruption_accumulator = 1.0;

        engine.tick(100.0);
        assert!(
            engine.corruption_accumulator < 1.0,
            "accumulator should decay over time"
        );
        assert!(
            engine.corruption_accumulator >= 0.0,
            "accumulator floors at 0"
        );
    }
}
