//! MCP server implementation: the `civis_*` tools plus the rmcp
//! `ServerHandler` glue. Lives in its own module so the
//! `#[tool_router]`-generated code is isolated from the public library
//! helpers in `lib.rs` (which intentionally avoid `rmcp` re-exports so
//! unit tests can compile without pulling in the macro-generated code).

use std::path::PathBuf;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{ServerCapabilities, ServerInfo},
    schemars::JsonSchema,
    tool, tool_handler, tool_router, Json,
};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use civis_cli::census::CensusConfig;

/// MCP server that exposes the verification tools (`civis_verify`,
/// `civis_pixels`, `civis_census`) plus 12 thin JSON-RPC forwarders that
/// proxy existing `civ-server` methods. The router is populated by the
/// `#[tool_router]` macro on the impl block below.
///
/// Each forwarder wraps an existing `civ-server` JSON-RPC method (see
/// `crates/server/src/jsonrpc.rs`). The shim does not invent backend
/// semantics — it just builds the envelope, opens a short-lived WS, and
/// returns the raw `result` JSON to the MCP caller.
#[derive(Clone, Default)]
pub struct CivisMcpServer {
    #[allow(dead_code)]
    tool_router: ToolRouter<Self>,
}

impl CivisMcpServer {
    /// Build a fresh server instance with an empty tool router. The router
    /// itself is generated by the `#[tool_router]` macro and picks up
    /// every `#[tool]` method on the impl block below.
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }
}

// ── shared argument types ────────────────────────────────────────────────

/// Common transport-override block (host/port/timeout) used by every
/// JSON-RPC forwarding tool. Mirrors `CensusArgs` so the existing
/// `civis_census` tool stays in lockstep.
#[derive(Debug, Default, Deserialize, JsonSchema)]
pub struct RpcArgs {
    /// Optional WebSocket host override. Default `127.0.0.1`.
    #[schemars(description = "WebSocket host override (env: CIV_WS_HOST)")]
    pub host: Option<String>,
    /// Optional WebSocket port override. Default 3000.
    #[schemars(description = "WebSocket port override (env: CIV_SERVER_PORT)")]
    pub port: Option<u16>,
    /// Optional per-request timeout in milliseconds. Default 5000.
    #[schemars(description = "Per-request timeout in ms (env: CIV_CENSUS_TIMEOUT_MS)")]
    pub timeout_ms: Option<u64>,
}

impl RpcArgs {
    /// Build a [`CensusConfig`] from env defaults + this arg's overrides.
    fn resolve_config(&self) -> CensusConfig {
        let mut config = crate::census_config_with_url();
        if let Some(host) = &self.host {
            config.host = host.clone();
        }
        if let Some(port) = self.port {
            config.port = port;
        }
        if let Some(timeout_ms) = self.timeout_ms {
            config.timeout_ms = timeout_ms;
        }
        config
    }
}

// ── existing argument types ──────────────────────────────────────────────

#[derive(Debug, Deserialize, JsonSchema)]
pub struct VerifyArgs {
    /// Optional explicit PNG output path. Defaults to
    /// `target/verify-frames/frame-0.png` (matches `civis-cli`'s verify bin).
    #[schemars(description = "Optional explicit output PNG path")]
    pub out: Option<String>,
    /// Optional window width in logical pixels (default 640).
    #[schemars(description = "Window width in logical pixels (default 640)")]
    pub width: Option<u32>,
    /// Optional window height in logical pixels (default 360).
    #[schemars(description = "Window height in logical pixels (default 360)")]
    pub height: Option<u32>,
    /// Optional settle frames before the screenshot is triggered.
    #[schemars(description = "Frames to wait before capture (default 60)")]
    pub settle_frames: Option<u32>,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct PixelsArgs {
    /// Path to a PNG file on disk. Use the path returned by `civis_verify`.
    pub path: String,
    /// Optional grid size (sample points per axis). Default 16.
    #[schemars(description = "Sample points per axis (default 16)")]
    pub grid: Option<u32>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct CensusArgs {
    /// Optional WebSocket host override. Default `127.0.0.1`.
    #[schemars(description = "WebSocket host override (env: CIV_WS_HOST)")]
    pub host: Option<String>,
    /// Optional WebSocket port override. Default 3000.
    #[schemars(description = "WebSocket port override (env: CIV_SERVER_PORT)")]
    pub port: Option<u16>,
    /// Optional per-request timeout in milliseconds. Default 5000.
    #[schemars(description = "Per-request timeout in ms (env: CIV_CENSUS_TIMEOUT_MS)")]
    pub timeout_ms: Option<u64>,
}

// ── god-tool verb argument types ─────────────────────────────────────────

/// Verb discriminator for `civis_god_action` (FR-CIV-GODTOOL). The
/// underlying `sim.god_action` JSON-RPC accepts these strings:
/// `smite | heal | place_terrain | ignite | spawn_creature | bless |
/// multiply_creatures`. The MCP tool re-exports the same enum so agents
/// get a typed payload instead of a free-form string.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum GodActionKind {
    /// `smite` — tactical damage blast at a normalized map point.
    Smite,
    /// `heal` — restore full health to every citizen near a point.
    Heal,
    /// `place_terrain` — paint voxels in a disk around a point with a
    /// chosen material id.
    PlaceTerrain,
    /// `ignite` — shorthand for `place_terrain` with the LAVA material id.
    Ignite,
    /// `spawn_creature` — drop a single civilian into the world.
    SpawnCreature,
    /// `bless` — bump `welfare` and `ideology` of nearby citizens.
    Bless,
    /// `multiply_creatures` — spawn N civilians within a disk
    /// (FR-CIV-GODTOOL-001).
    MultiplyCreatures,
}

impl GodActionKind {
    fn wire_name(self) -> &'static str {
        match self {
            Self::Smite => "smite",
            Self::Heal => "heal",
            Self::PlaceTerrain => "place_terrain",
            Self::Ignite => "ignite",
            Self::SpawnCreature => "spawn_creature",
            Self::Bless => "bless",
            Self::MultiplyCreatures => "multiply_creatures",
        }
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GodActionArgs {
    /// Verb to invoke — see [`GodActionKind`].
    pub action: GodActionKind,
    /// Normalized map X in `[0, 1]`.
    #[schemars(description = "Normalized map X in [0, 1]")]
    pub x: f32,
    /// Normalized map Y in `[0, 1]`.
    #[schemars(description = "Normalized map Y in [0, 1]")]
    pub y: f32,
    /// Optional brush radius in voxels (`smite`/`place_terrain`/`ignite`).
    #[schemars(description = "Brush radius in voxels (verb-specific clamp)")]
    pub radius: Option<u32>,
    /// Optional energy delivered by `smite` (clamped 0..=u32::MAX).
    #[schemars(description = "Energy delivered (smite only)")]
    pub energy: Option<u32>,
    /// Optional affected-radius in normalized units (`heal`/`bless`/
    /// `multiply_creatures`).
    #[schemars(description = "Normalized radius (heal/bless/multiply_creatures)")]
    pub radius_norm: Option<f32>,
    /// Optional magnitude for `bless` (clamped 0..=1).
    #[schemars(description = "Magnitude for bless verb (0..=1)")]
    pub magnitude: Option<f32>,
    /// Material id for `place_terrain` (0..=255).
    #[schemars(description = "Material id for place_terrain (0..=255)")]
    pub material: Option<u32>,
    /// Number of civilians for `multiply_creatures` (1..=32).
    #[schemars(description = "Civilian count for multiply_creatures (1..=32)")]
    pub count: Option<u32>,
    /// Faction id for `spawn_creature` / `multiply_creatures`.
    #[schemars(description = "Owning faction id")]
    pub faction: Option<u32>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

impl GodActionArgs {
    /// Build the JSON-RPC params object the bridge expects. Unknown
    /// fields are dropped server-side so we only forward what the
    /// selected verb understands (matches `parse_god_action` in
    /// `crates/server/src/jsonrpc.rs:2019`).
    fn to_params(&self) -> Value {
        let mut obj = serde_json::Map::new();
        obj.insert("action".to_owned(), json!(self.action.wire_name()));
        obj.insert("x".to_owned(), json!(self.x));
        obj.insert("y".to_owned(), json!(self.y));
        if let Some(radius) = self.radius {
            obj.insert("radius".to_owned(), json!(radius));
        }
        if let Some(energy) = self.energy {
            obj.insert("energy".to_owned(), json!(energy));
        }
        if let Some(radius_norm) = self.radius_norm {
            obj.insert("radius_norm".to_owned(), json!(radius_norm));
        }
        if let Some(magnitude) = self.magnitude {
            obj.insert("magnitude".to_owned(), json!(magnitude));
        }
        if let Some(material) = self.material {
            obj.insert("material".to_owned(), json!(material));
        }
        if let Some(count) = self.count {
            obj.insert("count".to_owned(), json!(count));
        }
        if let Some(faction) = self.faction {
            obj.insert("faction".to_owned(), json!(faction));
        }
        Value::Object(obj)
    }
}

// ── diplomacy verb argument types ────────────────────────────────────────

/// Verb discriminator for `civis_diplomacy_action`
/// (FR-CIV-CLIENT-006). The underlying `sim.diplomacy_action` method
/// accepts `propose_treaty | declare_war | offer_trade`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum DiplomacyActionKind {
    /// `propose_treaty` — open a peace treaty proposal.
    ProposeTreaty,
    /// `declare_war` — start a conflict.
    DeclareWar,
    /// `offer_trade` — open a trade route proposal.
    OfferTrade,
}

impl DiplomacyActionKind {
    fn wire_name(self) -> &'static str {
        match self {
            Self::ProposeTreaty => "propose_treaty",
            Self::DeclareWar => "declare_war",
            Self::OfferTrade => "offer_trade",
        }
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct DiplomacyActionArgs {
    /// Verb to invoke — see [`DiplomacyActionKind`].
    pub action: DiplomacyActionKind,
    /// Target faction id.
    pub target_faction: u32,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

// ── spawn-palette argument types ─────────────────────────────────────────

/// Palette kind for `civis_spawn_entity` (FR-CIV-UX-006). Matches the
/// wire labels in `crates/server/src/jsonrpc.rs:SpawnEntityKind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SpawnPaletteKind {
    /// `civilian` — single civilian.
    Civilian,
    /// `vehicle` — military vehicle (Knight).
    Vehicle,
    /// `airport` — civic hub (CityCenter).
    Airport,
    /// `port` — harbor / trade port (Market).
    Port,
    /// `hangar` — hangar / barracks (Barracks).
    Hangar,
}

impl SpawnPaletteKind {
    fn wire_name(self) -> &'static str {
        match self {
            Self::Civilian => "civilian",
            Self::Vehicle => "vehicle",
            Self::Airport => "airport",
            Self::Port => "port",
            Self::Hangar => "hangar",
        }
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SpawnEntityArgs {
    /// Palette kind — see [`SpawnPaletteKind`].
    pub kind: SpawnPaletteKind,
    /// Normalized map X in `[0, 1]`.
    pub x: f32,
    /// Normalized map Y in `[0, 1]`.
    pub y: f32,
    /// Owning faction id (defaults to 0 server-side).
    #[schemars(description = "Owning faction id (defaults to 0)")]
    pub faction: Option<u32>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

// ── tech / research / speed argument types ───────────────────────────────

#[derive(Debug, Deserialize, JsonSchema)]
pub struct QueueResearchArgs {
    /// Tech name to queue. Valid values are documented in
    /// `crates/server/src/jsonrpc.rs` (KNOWN_TECHS):
    /// `pottery, masonry, writing, iron_working, currency, mathematics,
    /// gunpowder, printing, banking, steam_power, electricity, railroad`.
    pub tech: String,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SpeedSetArgs {
    /// Tick speed multiplier — must be one of 0, 1, 2, 4, or 8
    /// (`ALLOWED_SPEED_MULTIPLIERS` in `crates/server/src/jsonrpc.rs`).
    pub multiplier: u32,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SimCommandAction {
    /// No-op command for scheduling compatibility.
    Noop,
    /// Advance exactly one simulation tick.
    Tick,
}

impl SimCommandAction {
    fn wire_name(self) -> &'static str {
        match self {
            Self::Noop => "noop",
            Self::Tick => "tick",
        }
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimCommandArgs {
    /// JSON-RPC command action — `noop` or `tick`.
    pub action: SimCommandAction,
    /// Optional role to satisfy operator-gated server methods.
    pub role: Option<String>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimResetArgs {
    /// Seed for the next simulation session.
    pub seed: u64,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimLoadScenarioArgs {
    /// Scenario preset name.
    pub preset: String,
    /// Optional seed override; when omitted, server defaults apply.
    pub seed: Option<u64>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimSetPolicyArgs {
    /// Economy scarcity multiplier.
    pub scarcity_multiplier: f64,
    /// Optional base consumption policy override in joules.
    pub base_consumption_joules: Option<u64>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimCommandlessArgs {
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SaveReplayArgs {
    /// Relative replay path; validation is enforced by `crates/server/src/jsonrpc.rs`.
    pub path: String,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SpawnCivilianArgs {
    /// Normalized map X in `[0, 1]`.
    pub x: f32,
    /// Normalized map Y in `[0, 1]`.
    pub y: f32,
    /// Owning faction id (defaults to 0).
    pub faction: Option<u32>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct PlaceVoxelArgs {
    /// World tile X.
    pub x: i64,
    /// World tile Y.
    pub y: i64,
    /// World tile Z.
    pub z: i64,
    /// Target voxel material ID.
    pub material: u16,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimDamageArgs {
    /// World tile X (integer).
    pub x: i64,
    /// World tile Y (integer).
    pub y: i64,
    /// World tile Z (integer).
    pub z: i64,
    /// Radius in voxels.
    pub radius: Option<u8>,
    /// Damage energy.
    pub energy: Option<u32>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct InspectTileArgs {
    /// World tile X (integer).
    pub x: i64,
    /// World tile Y (integer).
    pub y: i64,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SaveSlotArgs {
    /// Save slot name.
    pub slot_name: String,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimSubscriptionArgs {
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimInspectArgs {
    /// Optional integer tile X for optional probe projection.
    pub tile_x: Option<i64>,
    /// Optional integer tile Y for optional probe projection.
    pub tile_y: Option<i64>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimGetEmergenceArgs {
    /// Include legacy coarse metrics from `sim.get_emergence_metrics`.
    pub include_legacy: Option<bool>,
    /// Include `emergence.dashboard`.
    pub include_dashboard: Option<bool>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimStepArgs {
    /// Number of ticks to advance (default 1).
    pub ticks: Option<u64>,
    /// Optional temporary pause at step end via `sim.set_speed`.
    pub auto_pause: Option<bool>,
    /// Role passed through for operator checks when enabled.
    pub role: Option<String>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimRunUntilArgs {
    /// Mandatory tick budget.
    pub max_ticks: u64,
    /// Optional stopping tick threshold.
    pub target_tick: Option<u64>,
    /// Optional stopping outcome label (`ongoing`, `victory`, `defeat`, `draw`).
    pub target_outcome: Option<String>,
    /// Optional max wall clock time while polling.
    pub timeout_seconds: Option<u64>,
    /// Poll interval in ticks (default 8).
    pub poll_every: Option<u64>,
    /// Role passed through for operator checks when enabled.
    pub role: Option<String>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimSpawnArgs {
    /// Spawn kind mapped to `sim.spawn_entity`.
    pub kind: SpawnPaletteKind,
    /// Normalized map X in `[0, 1]`.
    pub x: f32,
    /// Normalized map Y in `[0, 1]`.
    pub y: f32,
    /// Owning faction id (defaults to 0).
    pub faction: Option<u32>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimSculptArgs {
    /// World tile X (integer).
    pub x: i64,
    /// World tile Y (integer).
    pub y: i64,
    /// World tile Z (integer).
    pub z: i64,
    /// Material ID forwarded to `sim.place_voxel`.
    pub material: u16,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimSpawnOrganismArgs {
    /// Number of civilians to spawn.
    pub count: u32,
    /// Normalized map X in `[0, 1]`.
    pub x: f32,
    /// Normalized map Y in `[0, 1]`.
    pub y: f32,
    /// Optional owning faction id.
    pub faction: Option<u32>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SimTerraformKind {
    Raise,
    Lower,
    Level,
    Smooth,
    Slope,
    Flatten,
    Shift,
    AddLand,
    DigOcean,
    RaiseMountain,
    DropBiome,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimTerraformExtentArgs {
    /// Brush center X in world coordinates.
    pub x: i64,
    /// Brush center Y in world coordinates.
    pub y: i64,
    /// Brush center Z in world coordinates.
    pub z: i64,
    /// Tool shape footprint, mapped to best-effort `sim.place_voxel` stamping.
    pub op: SimTerraformKind,
    /// Optional material id forwarded to `sim.place_voxel`.
    pub material: Option<u16>,
    /// Optional material stamp radius, ignored by `sim.place_voxel` fallback.
    pub radius: Option<u32>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SimDisasterKind {
    Meteor,
    Lightning,
    Flood,
    Quake,
    Firestorm,
    Tornado,
    VolcanicVent,
    Drought,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimDisasterArgs {
    /// Disaster family, currently best-effort mapped to `sim.damage`.
    pub kind: SimDisasterKind,
    /// World tile X (integer).
    pub x: i64,
    /// World tile Y (integer).
    pub y: i64,
    /// World tile Z (integer).
    pub z: i64,
    /// Damage radius in voxels.
    pub radius: Option<u8>,
    /// Damage energy.
    pub energy: Option<u32>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SimLawArgs {
    /// Economy law knob name. Mapped to nearest `sim.set_policy` field.
    pub law: String,
    /// Economy multiplier / law magnitude to map.
    pub value: Option<f64>,
    /// Optional `base_consumption_joules`.
    pub base_consumption_joules: Option<u64>,
    /// Transport override (host/port/timeout).
    #[serde(flatten)]
    pub transport: RpcArgs,
}

// ── existing result types ───────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct PixelsResult {
    pub path: String,
    pub grid: u32,
    pub stats: serde_json::Value,
    pub harness_version: &'static str,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct CensusResult {
    pub url: String,
    pub tick: u64,
    pub population: Option<u64>,
    pub live: bool,
    pub harness_version: &'static str,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct VerifyResultTool {
    pub output_path: String,
    pub settle_frames: u32,
    pub width: u32,
    pub height: u32,
    pub harness_version: &'static str,
    pub bevy_version: &'static str,
}

// ── new shared result envelope for JSON-RPC forwarders ──────────────────

/// Standard envelope returned by every JSON-RPC forwarding tool. Wraps
/// the raw `result` value the bridge returned so MCP clients can correlate
/// the tool call with the bridge wire shape (FR-CIV-MCP-003 contract test).
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct RpcForwardResult {
    /// The JSON-RPC method that was invoked.
    pub method: String,
    /// The bridge URL the request was sent to.
    pub url: String,
    /// The raw `result` value the bridge returned (shape is method-specific).
    pub result: serde_json::Value,
    /// Harness version stamp so agents can correlate evidence packets.
    pub harness_version: &'static str,
}

fn forward_rpc(
    transport: &RpcArgs,
    method: &str,
    params: Value,
    label: &str,
) -> Result<RpcForwardResult, String> {
    let config = transport.resolve_config();
    let url = config.ws_url();
    let result = crate::dispatch_rpc_method(&config, method, params)
        .map_err(|err| format!("{label}: {err}"))?;
    Ok(RpcForwardResult {
        method: method.to_owned(),
        url,
        result,
        harness_version: crate::HARNESS_VERSION,
    })
}

#[tool_router]
impl CivisMcpServer {
    /// Run the Bevy 0.18 frame-capture pipeline. Calls
    /// `civis_cli::verify::run_verify` directly — no `cargo run` shell-out.
    /// Returns a structured error when the `bevy` feature is disabled so
    /// agents that hit the path without rebuilding know exactly what to do.
    #[tool(
        name = "civis_verify",
        description = "Capture a single Bevy 0.18 frame to PNG and return the on-disk path. Requires the `bevy` feature at build time."
    )]
    async fn civis_verify(
        &self,
        Parameters(VerifyArgs {
            out,
            width,
            height,
            settle_frames,
        }): Parameters<VerifyArgs>,
    ) -> Result<Json<VerifyResultTool>, String> {
        #[cfg(feature = "bevy")]
        {
            use civis_cli::verify::{run_verify as cli_run_verify, VerifyOptions, BEVY_VERSION};

            let options = VerifyOptions {
                output_path: PathBuf::from(
                    out.unwrap_or_else(|| "target/verify-frames/frame-0.png".to_string()),
                ),
                settle_frames: settle_frames.unwrap_or(60),
                width: width.unwrap_or(640),
                height: height.unwrap_or(360),
            };
            let result = cli_run_verify(options).map_err(|err| format!("civis_verify: {err}"))?;
            Ok(Json(VerifyResultTool {
                output_path: result.output_path.to_string_lossy().to_string(),
                settle_frames: result.settle_frames,
                width: result.width,
                height: result.height,
                harness_version: civis_cli::HARNESS_VERSION,
                bevy_version: BEVY_VERSION,
            }))
        }
        #[cfg(not(feature = "bevy"))]
        {
            let _ = (out, width, height, settle_frames);
            Err("civis_verify requires the `bevy` feature; rebuild with `cargo build -p civis-mcp --features bevy`".to_string())
        }
    }

    /// Decode a PNG file and emit pixel statistics. Calls the pure
    /// `civis_cli::pixels::{sample_rgb_grid, compute_pixel_stats}` library
    /// functions; no Bevy or network involvement.
    #[tool(
        name = "civis_pixels",
        description = "Sample a regular RGB grid from a PNG file and emit pixel statistics (mean R/G/B, percent near-black, percent gray, distinct hue count). Pure offline — no renderer or network."
    )]
    async fn civis_pixels(
        &self,
        Parameters(PixelsArgs { path, grid }): Parameters<PixelsArgs>,
    ) -> Result<Json<PixelsResult>, String> {
        let grid_usize = grid.map(|g| g as usize).unwrap_or(16);
        let path_buf = PathBuf::from(&path);
        let payload = crate::pixels_tool_payload(&path_buf, grid_usize)?;
        let stats = payload
            .get("stats")
            .cloned()
            .ok_or_else(|| "pixels_tool_payload missing `stats`".to_string())?;
        Ok(Json(PixelsResult {
            path,
            grid: grid.unwrap_or(16),
            stats,
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    /// Query `sim.status` over the civ-server WebSocket JSON-RPC bridge.
    /// Calls `civis_cli::census::{build_sim_status_request, decode_response,
    /// validate_sim_status}` directly.
    #[tool(
        name = "civis_census",
        description = "Read sim.status from the civ-server JSON-RPC WebSocket bridge. Returns the live tick, population (if a sim is attached), and a derived `live` flag."
    )]
    async fn civis_census(
        &self,
        Parameters(CensusArgs {
            host,
            port,
            timeout_ms,
        }): Parameters<CensusArgs>,
    ) -> Result<Json<CensusResult>, String> {
        let mut config = crate::census_config_with_url();
        if let Some(host) = host {
            config.host = host;
        }
        if let Some(port) = port {
            config.port = port;
        }
        if let Some(timeout_ms) = timeout_ms {
            config.timeout_ms = timeout_ms;
        }
        let url = config.ws_url();
        let status =
            crate::census_sim_status(&config).map_err(|err| format!("civis_census: {err}"))?;
        Ok(Json(CensusResult {
            url,
            tick: status.tick,
            population: status.population,
            live: status.live,
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    // ── JSON-RPC forwarders (FR-CIV-MCP-001) ────────────────────────────

    /// Forward `health` to civ-server. Returns the bridge-reported tick
    /// (or 0 when no simulation is loaded).
    #[tool(
        name = "civis_health",
        description = "Probe civ-server liveness via the JSON-RPC `health` method. Returns the bridge tick as a sanity check."
    )]
    async fn civis_health(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "health", json!({}), "civis_health").map(Json)
    }

    /// Forward `sim.snapshot` to civ-server. Returns the full snapshot
    /// (census + market prices + emergence + climate + spectator pins).
    #[tool(
        name = "civis_snapshot",
        description = "Forward sim.snapshot to civ-server. Returns the full bridge snapshot (tick, population, building_count, energy_budget, market_prices, hash_chain_root, emergence block, climate, spectator pins)."
    )]
    async fn civis_snapshot(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.snapshot", json!({}), "civis_snapshot").map(Json)
    }

    /// Forward `sim.emergence` to civ-server. Returns the latest emergence
    /// sample (or `null` for ticks 0..49 before the first sample boundary).
    #[tool(
        name = "civis_emergence",
        description = "Forward sim.emergence to civ-server. Returns the latest civ-emergence-metrics sample (entropy_bits, entropy_norm, structure counts, branching regime, dashboard block)."
    )]
    async fn civis_emergence(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.emergence", json!({}), "civis_emergence").map(Json)
    }

    /// Forward `sim.snapshot` and project the `market_prices` field so
    /// dashboards don't have to fetch the full snapshot just to read
    /// clearing prices.
    #[tool(
        name = "civis_market_prices",
        description = "Forward sim.snapshot and project the `market_prices` field. Returns `{<good>: <cents>}` for every good the bridge currently knows about (FR-CIV-EMERG-002 surface)."
    )]
    async fn civis_market_prices(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let config = transport.resolve_config();
        let url = config.ws_url();
        let snapshot = crate::dispatch_rpc_method(&config, "sim.snapshot", json!({}))
            .map_err(|err| format!("civis_market_prices: {err}"))?;
        let prices = snapshot
            .get("market_prices")
            .cloned()
            .unwrap_or_else(|| serde_json::json!({}));
        Ok(Json(RpcForwardResult {
            method: "sim.snapshot".to_owned(),
            url,
            result: prices,
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    /// Forward `sim.get_speed` to civ-server. Returns the current tick
    /// speed multiplier.
    #[tool(
        name = "civis_speed_get",
        description = "Forward sim.get_speed to civ-server. Returns the current tick speed multiplier (0/1/2/4/8)."
    )]
    async fn civis_speed_get(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_speed", json!({}), "civis_speed_get").map(Json)
    }

    /// Forward `sim.set_speed` to civ-server. Multiplier must be one of
    /// 0/1/2/4/8 — the bridge rejects other values with `INVALID_PARAMS`.
    #[tool(
        name = "civis_speed_set",
        description = "Forward sim.set_speed to civ-server. Multiplier must be 0, 1, 2, 4, or 8 (ALLOWED_SPEED_MULTIPLIERS)."
    )]
    async fn civis_speed_set(
        &self,
        Parameters(SpeedSetArgs {
            multiplier,
            transport,
        }): Parameters<SpeedSetArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.set_speed",
            json!({ "multiplier": multiplier }),
            "civis_speed_set",
        )
        .map(Json)
    }

    /// Forward `sim.status` to civ-server. Returns sim attachment details and
    /// latest population summary when available.
    #[tool(
        name = "civis_status",
        description = "Forward sim.status to civ-server. Returns sim status fields (population if snapshot exists, live flag, current tick)."
    )]
    async fn civis_status(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.status", json!({}), "civis_status").map(Json)
    }

    /// Forward `sim.get_tick` to civ-server. Returns current sim tick and
    /// wall-clock game time.
    #[tool(
        name = "civis_get_tick",
        description = "Forward sim.get_tick to civ-server. Returns the current simulation tick and wall-clock time metadata."
    )]
    async fn civis_get_tick(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_tick", json!({}), "civis_get_tick").map(Json)
    }

    /// Forward `sim.get_factions` to civ-server. Returns faction summaries.
    #[tool(
        name = "civis_factions",
        description = "Forward sim.get_factions to civ-server. Returns faction summary rows from the current snapshot."
    )]
    async fn civis_factions(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_factions", json!({}), "civis_factions").map(Json)
    }

    /// Forward `sim.get_resources` to civ-server. Returns resource summaries.
    #[tool(
        name = "civis_resources",
        description = "Forward sim.get_resources to civ-server. Returns world-level resource summaries."
    )]
    async fn civis_resources(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_resources", json!({}), "civis_resources").map(Json)
    }

    /// Forward `sim.get_emergence_metrics` to civ-server.
    #[tool(
        name = "civis_emergence_metrics",
        description = "Forward sim.get_emergence_metrics to civ-server. Returns coarse, transport-safe emergence metrics."
    )]
    async fn civis_emergence_metrics(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_emergence_metrics", json!({}), "civis_emergence_metrics").map(Json)
    }

    /// Forward `emergence.metrics` to civ-server. Returns full emergence
    /// analytics payload (`entropy_bits`, structure counts, power-law slope).
    #[tool(
        name = "civis_emergence_metrics_full",
        description = "Forward emergence.metrics to civ-server. Returns the full FR-CIV-EMERG-001..005 analytic block."
    )]
    async fn civis_emergence_metrics_full(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "emergence.metrics", json!({}), "civis_emergence_metrics_full").map(Json)
    }

    /// Forward `emergence.dashboard` to civ-server.
    #[tool(
        name = "civis_emergence_dashboard",
        description = "Forward emergence.dashboard to civ-server. Returns the compact dashboard sample for UI polling."
    )]
    async fn civis_emergence_dashboard(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "emergence.dashboard",
            json!({}),
            "civis_emergence_dashboard",
        )
        .map(Json)
    }

    /// Forward `sim.command` to civ-server (`action`: `noop` or `tick`;
    /// optional `role` passes through for operator-gated action checks).
    #[tool(
        name = "civis_sim_command",
        description = "Forward sim.command to civ-server. Pass `action=tick` (optionally with role=operator) to advance simulation."
    )]
    async fn civis_sim_command(
        &self,
        Parameters(SimCommandArgs {
            action,
            role,
            transport,
        }): Parameters<SimCommandArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut params = serde_json::Map::new();
        params.insert("action".to_owned(), json!(action.wire_name()));
        if let Some(role) = role {
            params.insert("role".to_owned(), json!(role));
        }
        forward_rpc(&transport, "sim.command", Value::Object(params), "civis_sim_command").map(Json)
    }

    /// Forward `sim.reset` to civ-server.
    #[tool(
        name = "civis_reset",
        description = "Forward sim.reset to civ-server. Replace simulation with a fresh seeded instance."
    )]
    async fn civis_reset(
        &self,
        Parameters(SimResetArgs { seed, transport }): Parameters<SimResetArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.reset", json!({ "seed": seed }), "civis_reset").map(Json)
    }

    /// Forward `sim.load_scenario` to civ-server.
    #[tool(
        name = "civis_load_scenario",
        description = "Forward sim.load_scenario to civ-server. Start a named scenario preset with optional seed override."
    )]
    async fn civis_load_scenario(
        &self,
        Parameters(SimLoadScenarioArgs {
            preset,
            seed,
            transport,
        }): Parameters<SimLoadScenarioArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut params = serde_json::Map::new();
        params.insert("preset".to_owned(), json!(preset));
        if let Some(seed) = seed {
            params.insert("seed".to_owned(), json!(seed));
        }
        forward_rpc(
            &transport,
            "sim.load_scenario",
            Value::Object(params),
            "civis_load_scenario",
        )
        .map(Json)
    }

    /// Forward `sim.set_policy` to civ-server.
    #[tool(
        name = "civis_set_policy",
        description = "Forward sim.set_policy to civ-server. Update economy policy values (`scarcity_multiplier`, optional `base_consumption_joules`)."
    )]
    async fn civis_set_policy(
        &self,
        Parameters(SimSetPolicyArgs {
            scarcity_multiplier,
            base_consumption_joules,
            transport,
        }): Parameters<SimSetPolicyArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut params = serde_json::Map::new();
        params.insert("scarcity_multiplier".to_owned(), json!(scarcity_multiplier));
        if let Some(base_consumption_joules) = base_consumption_joules {
            params.insert("base_consumption_joules".to_owned(), json!(base_consumption_joules));
        }
        forward_rpc(&transport, "sim.set_policy", Value::Object(params), "civis_set_policy").map(Json)
    }

    /// Forward `sim.save_replay` to civ-server.
    #[tool(
        name = "civis_save_replay",
        description = "Forward sim.save_replay to civ-server. Persist in-memory replay log to a `.civreplay` file."
    )]
    async fn civis_save_replay(
        &self,
        Parameters(SaveReplayArgs { path, transport }): Parameters<SaveReplayArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.save_replay", json!({ "path": path }), "civis_save_replay").map(Json)
    }

    /// Forward `sim.load_replay` to civ-server.
    #[tool(
        name = "civis_load_replay",
        description = "Forward sim.load_replay to civ-server. Reload simulation state from a `.civreplay` file."
    )]
    async fn civis_load_replay(
        &self,
        Parameters(SaveReplayArgs { path, transport }): Parameters<SaveReplayArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.load_replay", json!({ "path": path }), "civis_load_replay").map(Json)
    }

    /// Forward `sim.spawn_civilian` to civ-server.
    #[tool(
        name = "civis_spawn_civilian",
        description = "Forward sim.spawn_civilian to civ-server. Spawn one civilian at normalized map coordinates."
    )]
    async fn civis_spawn_civilian(
        &self,
        Parameters(SpawnCivilianArgs {
            x,
            y,
            faction,
            transport,
        }): Parameters<SpawnCivilianArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut params = serde_json::Map::new();
        params.insert("x".to_owned(), json!(x));
        params.insert("y".to_owned(), json!(y));
        if let Some(faction) = faction {
            params.insert("faction".to_owned(), json!(faction));
        }
        forward_rpc(
            &transport,
            "sim.spawn_civilian",
            Value::Object(params),
            "civis_spawn_civilian",
        )
        .map(Json)
    }

    /// Forward `sim.place_voxel` to civ-server.
    #[tool(
        name = "civis_place_voxel",
        description = "Forward sim.place_voxel to civ-server. Place or overwrite one voxel at integer world coordinates."
    )]
    async fn civis_place_voxel(
        &self,
        Parameters(PlaceVoxelArgs {
            x,
            y,
            z,
            material,
            transport,
        }): Parameters<PlaceVoxelArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.place_voxel",
            json!({
                "x": x,
                "y": y,
                "z": z,
                "material": material,
            }),
            "civis_place_voxel",
        )
        .map(Json)
    }

    /// Forward `sim.damage` to civ-server.
    #[tool(
        name = "civis_damage",
        description = "Forward sim.damage to civ-server. Queue tactical damage at voxel coordinates."
    )]
    async fn civis_damage(
        &self,
        Parameters(SimDamageArgs {
            x,
            y,
            z,
            radius,
            energy,
            transport,
        }): Parameters<SimDamageArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut params = serde_json::Map::new();
        params.insert("x".to_owned(), json!(x));
        params.insert("y".to_owned(), json!(y));
        params.insert("z".to_owned(), json!(z));
        if let Some(radius) = radius {
            params.insert("radius".to_owned(), json!(radius));
        }
        if let Some(energy) = energy {
            params.insert("energy".to_owned(), json!(energy));
        }
        forward_rpc(&transport, "sim.damage", Value::Object(params), "civis_damage").map(Json)
    }

    /// Forward `sim.inspect_tile` to civ-server.
    #[tool(
        name = "civis_inspect_tile",
        description = "Forward sim.inspect_tile to civ-server. Inspect faction/resource terrain details at a map tile."
    )]
    async fn civis_inspect_tile(
        &self,
        Parameters(InspectTileArgs { x, y, transport }): Parameters<InspectTileArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.inspect_tile",
            json!({ "x": x, "y": y }),
            "civis_inspect_tile",
        )
        .map(Json)
    }

    /// Forward `save.slot` to civ-server. Persists a production slot archive.
    #[tool(
        name = "civis_save_slot",
        description = "Forward save.slot to civ-server. Persist the simulation into a production save slot."
    )]
    async fn civis_save_slot(
        &self,
        Parameters(SaveSlotArgs {
            slot_name,
            transport,
        }): Parameters<SaveSlotArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "save.slot", json!({ "slot_name": slot_name }), "civis_save_slot").map(Json)
    }

    /// Forward `save.load` to civ-server. Restores from a named production slot.
    #[tool(
        name = "civis_load_slot",
        description = "Forward save.load to civ-server. Restore the simulation from a production save slot."
    )]
    async fn civis_load_slot(
        &self,
        Parameters(SaveSlotArgs {
            slot_name,
            transport,
        }): Parameters<SaveSlotArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "save.load", json!({ "slot_name": slot_name }), "civis_load_slot").map(Json)
    }

    /// Forward `sim.subscribe` to civ-server. Opens or updates a per-connection
    /// subscription filter.
    #[tool(
        name = "civis_subscribe",
        description = "Forward sim.subscribe to civ-server. Enable a per-connection event stream filter on current websocket session."
    )]
    async fn civis_subscribe(
        &self,
        Parameters(SimSubscriptionArgs { transport }): Parameters<SimSubscriptionArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.subscribe", json!({}), "civis_subscribe").map(Json)
    }

    /// Forward `sim.unsubscribe` to civ-server. Clears subscription filter.
    #[tool(
        name = "civis_unsubscribe",
        description = "Forward sim.unsubscribe to civ-server. Clear the current per-connection tick broadcast filter."
    )]
    async fn civis_unsubscribe(
        &self,
        Parameters(SimSubscriptionArgs { transport }): Parameters<SimSubscriptionArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.unsubscribe", json!({}), "civis_unsubscribe").map(Json)
    }

    /// Forward `sim.update_subscription` to civ-server. Replaces a per-connection
    /// subscription filter.
    #[tool(
        name = "civis_update_subscription",
        description = "Forward sim.update_subscription to civ-server. Replace an existing per-connection filter."
    )]
    async fn civis_update_subscription(
        &self,
        Parameters(SimSubscriptionArgs { transport }): Parameters<SimSubscriptionArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.update_subscription",
            json!({}),
            "civis_update_subscription",
        )
        .map(Json)
    }

    /// Forward `sim.outcome` to civ-server.
    #[tool(
        name = "civis_outcome",
        description = "Forward sim.outcome to civ-server. Returns precomputed game outcome block and win condition metadata."
    )]
    async fn civis_outcome(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.outcome", json!({}), "civis_outcome").map(Json)
    }

    /// Forward `sim.perf` to civ-server.
    #[tool(
        name = "civis_perf",
        description = "Forward sim.perf to civ-server. Returns lightweight server-side timing counters."
    )]
    async fn civis_perf(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.perf", json!({}), "civis_perf").map(Json)
    }

    /// Forward `sim.god_action` to civ-server. Use [`GodActionKind`] for a
    /// typed verb; the bridge parses the same verbs the Bevy/Godot/Unreal
    /// clients do, so verb-specific clamps are enforced server-side.
    #[tool(
        name = "civis_god_action",
        description = "Forward sim.god_action to civ-server. Sends a god-tool verb (smite, heal, place_terrain, ignite, spawn_creature, bless, multiply_creatures) at a normalized map point. Verb-specific clamps are enforced server-side (FR-CIV-GODTOOL)."
    )]
    async fn civis_god_action(
        &self,
        Parameters(args): Parameters<GodActionArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &args.transport,
            "sim.god_action",
            args.to_params(),
            "civis_god_action",
        )
        .map(Json)
    }

    /// Forward `sim.spawn_entity` to civ-server. Spawns a civilian,
    /// vehicle, airport, port, or hangar at a normalized map point.
    #[tool(
        name = "civis_spawn_entity",
        description = "Forward sim.spawn_entity to civ-server. Spawn a civilian / vehicle / airport / port / hangar at a normalized map point (FR-CIV-UX-006)."
    )]
    async fn civis_spawn_entity(
        &self,
        Parameters(SpawnEntityArgs {
            kind,
            x,
            y,
            faction,
            transport,
        }): Parameters<SpawnEntityArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut params = serde_json::Map::new();
        params.insert("kind".to_owned(), json!(kind.wire_name()));
        params.insert("x".to_owned(), json!(x));
        params.insert("y".to_owned(), json!(y));
        if let Some(faction) = faction {
            params.insert("faction".to_owned(), json!(faction));
        }
        forward_rpc(
            &transport,
            "sim.spawn_entity",
            Value::Object(params),
            "civis_spawn_entity",
        )
        .map(Json)
    }

    /// Forward `sim.diplomacy_action` to civ-server. Propose a treaty,
    /// declare war, or offer a trade route to a target faction.
    #[tool(
        name = "civis_diplomacy_action",
        description = "Forward sim.diplomacy_action to civ-server. Issue propose_treaty / declare_war / offer_trade against a target faction (FR-CIV-CLIENT-006)."
    )]
    async fn civis_diplomacy_action(
        &self,
        Parameters(DiplomacyActionArgs {
            action,
            target_faction,
            transport,
        }): Parameters<DiplomacyActionArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.diplomacy_action",
            json!({
                "action": action.wire_name(),
                "target_faction": target_faction,
            }),
            "civis_diplomacy_action",
        )
        .map(Json)
    }

    /// Forward `sim.queue_research` to civ-server. The bridge validates
    /// the tech name against the 12 known FR-CIV-SERVER-003 names and
    /// returns `INVALID_PARAMS` for unknowns.
    #[tool(
        name = "civis_research_queue",
        description = "Forward sim.queue_research to civ-server. Queue one of the 12 known techs (pottery, masonry, writing, iron_working, currency, mathematics, gunpowder, printing, banking, steam_power, electricity, railroad)."
    )]
    async fn civis_research_queue(
        &self,
        Parameters(QueueResearchArgs { tech, transport }): Parameters<QueueResearchArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.queue_research",
            json!({ "tech": tech }),
            "civis_research_queue",
        )
        .map(Json)
    }

    /// Forward `sim.tech_state` to civ-server. Returns the available,
    /// researched, and in-progress techs.
    #[tool(
        name = "civis_tech_state",
        description = "Forward sim.tech_state to civ-server. Returns the list of available techs plus the currently-researched and in-progress techs (FR-CIV-SERVER-003)."
    )]
    async fn civis_tech_state(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.tech_state", json!({}), "civis_tech_state").map(Json)
    }

    /// Forward `save.list` to civ-server. Returns the bridge `saves/`
    /// directory contents (production slot archives).
    #[tool(
        name = "civis_save_list",
        description = "Forward save.list to civ-server. Returns the bridge saves/ directory contents (production slot archives from CIV-1000 §13)."
    )]
    async fn civis_save_list(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "save.list", json!({}), "civis_save_list").map(Json)
    }

    /// Forward `health` to civ-server (control-surface alias: `sim_health`).
    #[tool(
        name = "sim_health",
        description = "Forward `health` to civ-server. Returns the bridge tick as a sanity check."
    )]
    async fn sim_health(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "health", json!({}), "sim_health").map(Json)
    }

    /// Forward `sim.snapshot` and optionally project an `sim.inspect_tile` probe.
    #[tool(
        name = "sim_inspect",
        description = "Forward sim.snapshot to civ-server. Optionally include `sim.inspect_tile` probe data."
    )]
    async fn sim_inspect(
        &self,
        Parameters(SimInspectArgs {
            tile_x,
            tile_y,
            transport,
        }): Parameters<SimInspectArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let snapshot = forward_rpc(
            &transport,
            "sim.snapshot",
            json!({}),
            "sim_inspect.snapshot",
        )?;

        let mut result = if snapshot.result.is_object() {
            snapshot.result
        } else {
            json!({ "snapshot": snapshot.result })
        };

        if let (Some(x), Some(y)) = (tile_x, tile_y) {
            let tile = forward_rpc(
                &transport,
                "sim.inspect_tile",
                json!({ "x": x, "y": y }),
                "sim_inspect.tile",
            )?;
            match &mut result {
                Value::Object(obj) => {
                    obj.insert("tile".to_owned(), tile.result);
                }
                _ => {
                    result = json!({ "snapshot": result, "tile": tile.result });
                }
            }
        }

        Ok(Json(RpcForwardResult {
            method: "sim_inspect".to_string(),
            url: snapshot.url,
            result,
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    /// Alias to `sim.status` for control-surface clients.
    #[tool(
        name = "sim_status",
        description = "Forward sim.status to civ-server. Use for heartbeat / liveness checks."
    )]
    async fn sim_status(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.status", json!({}), "sim_status").map(Json)
    }

    /// Alias to `sim.inspect_tile` for control-surface clients.
    #[tool(
        name = "sim_inspect_tile",
        description = "Forward sim.inspect_tile to civ-server."
    )]
    async fn sim_inspect_tile(
        &self,
        Parameters(InspectTileArgs { x, y, transport }): Parameters<InspectTileArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.inspect_tile",
            json!({ "x": x, "y": y }),
            "sim_inspect_tile",
        )
        .map(Json)
    }

    /// Alias to `sim.get_factions` for faction telemetry.
    #[tool(
        name = "sim_get_factions",
        description = "Forward sim.get_factions to civ-server."
    )]
    async fn sim_get_factions(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_factions", json!({}), "sim_get_factions").map(Json)
    }

    /// Alias to `sim.get_resources` for world resource telemetry.
    #[tool(
        name = "sim_get_resources",
        description = "Forward sim.get_resources to civ-server."
    )]
    async fn sim_get_resources(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_resources", json!({}), "sim_get_resources").map(Json)
    }

    /// Forward `sim.emergence` (+ optional legacy/detail side calls) to civ-server.
    #[tool(
        name = "sim_get_emergence",
        description = "Forward sim.emergence (and optional sim.get_emergence_metrics / emergence.dashboard) to civ-server."
    )]
    async fn sim_get_emergence(
        &self,
        Parameters(SimGetEmergenceArgs {
            include_legacy,
            include_dashboard,
            transport,
        }): Parameters<SimGetEmergenceArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let primary = forward_rpc(&transport, "sim.emergence", json!({}), "sim_get_emergence.primary")?;
        let mut merged = if primary.result.is_object() {
            primary.result
        } else {
            json!({ "emergence": primary.result })
        };
        if let Value::Object(ref mut obj) = merged {
            if include_legacy.unwrap_or(false) {
                let legacy = forward_rpc(
                    &transport,
                    "sim.get_emergence_metrics",
                    json!({}),
                    "sim_get_emergence.legacy",
                )?;
                obj.insert("legacy".to_owned(), legacy.result);
            }
            if include_dashboard.unwrap_or(false) {
                let dashboard = forward_rpc(
                    &transport,
                    "emergence.dashboard",
                    json!({}),
                    "sim_get_emergence.dashboard",
                )?;
                obj.insert("dashboard".to_owned(), dashboard.result);
            }
        }
        Ok(Json(RpcForwardResult {
            method: "sim_get_emergence".to_string(),
            url: primary.url,
            result: merged,
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    /// Alias to `sim.get_factions` plus lightweight diplomacy view.
    #[tool(
        name = "sim_get_diplomacy",
        description = "Alias surface for diplomacy read telemetry. Uses sim.get_factions today."
    )]
    async fn sim_get_diplomacy(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_factions", json!({}), "sim_get_diplomacy").map(Json)
    }

    /// Alias to `sim.tech_state` for research telemetry.
    #[tool(
        name = "sim_get_tech",
        description = "Forward sim.tech_state to civ-server."
    )]
    async fn sim_get_tech(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.tech_state", json!({}), "sim_get_tech").map(Json)
    }

    /// Alias to `sim.outcome` for game-state end-condition telemetry.
    #[tool(
        name = "sim_get_outcome",
        description = "Forward sim.outcome to civ-server."
    )]
    async fn sim_get_outcome(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.outcome", json!({}), "sim_get_outcome").map(Json)
    }

    /// Alias to `sim.command` repeated for N-tick stepping.
    #[tool(
        name = "sim_step",
        description = "Advance simulation by repeated sim.command tick calls."
    )]
    async fn sim_step(
        &self,
        Parameters(SimStepArgs {
            ticks,
            auto_pause,
            role,
            transport,
        }): Parameters<SimStepArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let ticks = ticks.unwrap_or(1).max(1);
        if auto_pause.unwrap_or(false) {
            let mut speed_params = serde_json::Map::new();
            speed_params.insert("multiplier".to_owned(), json!(0_u32));
            forward_rpc(&transport, "sim.set_speed", Value::Object(speed_params), "sim_step.pause").map_err(|e| {
                format!("sim_step: {e}")
            })?;
        }
        for _ in 0..ticks {
            let mut params = serde_json::Map::new();
            params.insert("action".to_owned(), json!(SimCommandAction::Tick.wire_name()));
            if let Some(role) = role.clone() {
                params.insert("role".to_owned(), json!(role));
            }
            forward_rpc(&transport, "sim.command", Value::Object(params), "sim_step.tick")
                .map_err(|e| format!("sim_step: {e}"))?;
        }
        if auto_pause.unwrap_or(false) {
            let mut speed_params = serde_json::Map::new();
            speed_params.insert("multiplier".to_owned(), json!(1_u32));
            forward_rpc(&transport, "sim.set_speed", Value::Object(speed_params), "sim_step.resume").map_err(|e| {
                format!("sim_step: {e}")
            })?;
        }
        let tick = forward_rpc(&transport, "sim.get_tick", json!({}), "sim_step.tick")?;
        let final_tick = tick
            .result
            .get("tick")
            .and_then(|v| v.as_u64())
            .unwrap_or(0);
        Ok(Json(RpcForwardResult {
            method: "sim_step".to_owned(),
            url: tick.url,
            result: json!({
                "ticks_advanced": ticks,
                "tick": final_tick,
            }),
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    /// Alias to `sim.set_speed` through control-surface naming.
    #[tool(
        name = "sim_set_speed",
        description = "Forward sim.set_speed to civ-server."
    )]
    async fn sim_set_speed(
        &self,
        Parameters(SpeedSetArgs {
            multiplier,
            transport,
        }): Parameters<SpeedSetArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.set_speed",
            json!({ "multiplier": multiplier }),
            "sim_set_speed",
        )
        .map(Json)
    }

    /// Alias to `sim.get_speed` for control-surface callers.
    #[tool(
        name = "sim_get_speed",
        description = "Forward sim.get_speed to civ-server."
    )]
    async fn sim_get_speed(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.get_speed", json!({}), "sim_get_speed").map(Json)
    }

    /// Run forward ticks until an endpoint condition is reached.
    #[tool(
        name = "sim_run_until",
        description = "Advance simulation in sim.command loops until target tick/outcome or max_ticks."
    )]
    async fn sim_run_until(
        &self,
        Parameters(SimRunUntilArgs {
            max_ticks,
            target_tick,
            target_outcome,
            timeout_seconds,
            poll_every,
            role,
            transport,
        }): Parameters<SimRunUntilArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let deadline_seconds = timeout_seconds.unwrap_or(0);
        let poll_every = poll_every.unwrap_or(8).max(1);
        let target_outcome = target_outcome
            .unwrap_or_else(|| "ongoing".to_owned())
            .to_lowercase();
        let target_tick = target_tick.unwrap_or(u64::MAX);
        let mut ticks: u64 = 0;
        let mut final_tick: u64 = 0;
        let mut final_outcome = "ongoing".to_owned();

        let timeout_deadline = std::time::Instant::now();
        let mut stopped = "max_ticks".to_owned();

        loop {
            if ticks >= max_ticks {
                break;
            }

            let mut params = serde_json::Map::new();
            params.insert("action".to_owned(), json!(SimCommandAction::Tick.wire_name()));
            if let Some(role) = role.clone() {
                params.insert("role".to_owned(), json!(role.clone()));
            }
            forward_rpc(&transport, "sim.command", Value::Object(params), "sim_run_until.tick")
                .map_err(|e| format!("sim_run_until: {e}"))?;
            ticks += 1;

            let should_poll = (ticks % poll_every == 0) || (ticks >= max_ticks) || (final_outcome != "ongoing");
            if should_poll {
                let outcome = forward_rpc(
                    &transport,
                    "sim.outcome",
                    json!({}),
                    "sim_run_until.outcome",
                )
                .map_err(|e| format!("sim_run_until: {e}"))?;
                final_outcome = outcome
                    .result
                    .get("outcome")
                    .and_then(Value::as_str)
                    .unwrap_or("ongoing")
                    .to_owned();

                let tick = forward_rpc(
                    &transport,
                    "sim.get_tick",
                    json!({}),
                    "sim_run_until.tick_check",
                )
                .map_err(|e| format!("sim_run_until: {e}"))?;
                final_tick = tick.result.get("tick").and_then(Value::as_u64).unwrap_or(ticks);

                if !target_outcome.is_empty() && final_outcome == target_outcome {
                    stopped = "target_outcome".to_owned();
                    break;
                }
            }

            if final_tick >= target_tick {
                stopped = "target_tick".to_owned();
                break;
            }

            if deadline_seconds > 0 && timeout_deadline.elapsed().as_secs() >= timeout_seconds {
                stopped = "timeout".to_owned();
                break;
            }
        }

        if final_tick == 0 {
            final_tick = forward_rpc(
                &transport,
                "sim.get_tick",
                json!({}),
                "sim_run_until.final_tick",
            )
            .map_err(|e| format!("sim_run_until: {e}"))?
            .result
            .get("tick")
            .and_then(Value::as_u64)
            .unwrap_or(final_tick);
        }

        Ok(Json(RpcForwardResult {
            method: "sim_run_until".to_owned(),
            url: forward_rpc(
                &transport,
                "health",
                json!({}),
                "sim_run_until.url",
            )?
            .url,
            result: json!({
                "ticks_advanced": ticks,
                "final_tick": final_tick,
                "final_outcome": final_outcome,
                "stopped_reason": stopped,
            }),
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    /// Alias to `sim.reset` for control-surface naming.
    #[tool(
        name = "sim_reset",
        description = "Alias for sim.reset."
    )]
    async fn sim_reset(
        &self,
        Parameters(SimResetArgs { seed, transport }): Parameters<SimResetArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.reset", json!({ "seed": seed }), "sim_reset").map(Json)
    }

    /// Alias to `sim.load_scenario` for control-surface naming.
    #[tool(
        name = "sim_load_scenario",
        description = "Alias for sim.load_scenario."
    )]
    async fn sim_load_scenario(
        &self,
        Parameters(SimLoadScenarioArgs {
            preset,
            seed,
            transport,
        }): Parameters<SimLoadScenarioArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut params = serde_json::Map::new();
        params.insert("preset".to_owned(), json!(preset));
        if let Some(seed) = seed {
            params.insert("seed".to_owned(), json!(seed));
        }
        forward_rpc(
            &transport,
            "sim.load_scenario",
            Value::Object(params),
            "sim_load_scenario",
        )
        .map(Json)
    }

    /// Alias to `sim_spawn_entity` and `sim.spawn_civilian` for mutating entities.
    #[tool(
        name = "sim_spawn",
        description = "Spawn one civ-agent entity or civilian at a map position."
    )]
    async fn sim_spawn(
        &self,
        Parameters(SimSpawnArgs {
            kind,
            x,
            y,
            faction,
            transport,
        }): Parameters<SimSpawnArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut result = forward_rpc(
            &transport,
            "sim.spawn_entity",
            json!({
                "kind": kind.wire_name(),
                "x": x,
                "y": y,
                "faction": faction.unwrap_or(0),
            }),
            "sim_spawn",
        );
        if kind == SpawnPaletteKind::Civilian && result.is_err() {
            result = forward_rpc(
                &transport,
                "sim.spawn_civilian",
                json!({
                    "x": x,
                    "y": y,
                    "faction": faction.unwrap_or(0),
                }),
                "sim_spawn_fallback",
            );
        }
        result.map(Json)
    }

    /// Alias to `sim.place_voxel` for mutating terrain.
    #[tool(
        name = "sim_sculpt",
        description = "Alias for sim.place_voxel."
    )]
    async fn sim_sculpt(
        &self,
        Parameters(SimSculptArgs {
            x,
            y,
            z,
            material,
            transport,
        }): Parameters<SimSculptArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.place_voxel",
            json!({ "x": x, "y": y, "z": z, "material": material }),
            "sim_sculpt",
        )
        .map(Json)
    }

    /// Best-effort `sim.place_voxel` fallback for missing `sim.terraform_extent`.
    #[tool(
        name = "sim_terraform_extent",
        description = "Best-effort terrain brush operation. Degrades to repeated sim.place_voxel until dedicated tool lands."
    )]
    async fn sim_terraform_extent(
        &self,
        Parameters(SimTerraformExtentArgs {
            x,
            y,
            z,
            _op,
            material,
            _radius,
            transport,
        }): Parameters<SimTerraformExtentArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let material = material.unwrap_or(1);
        forward_rpc(
            &transport,
            "sim.place_voxel",
            json!({ "x": x, "y": y, "z": z, "material": material }),
            "sim_terraform_extent",
        )
        .map(Json)
    }

    /// Best-effort disaster tool mapping to `sim.damage`.
    #[tool(
        name = "sim_disaster",
        description = "Best-effort disaster mapping to sim.damage."
    )]
    async fn sim_disaster(
        &self,
        Parameters(SimDisasterArgs {
            kind: _kind,
            x,
            y,
            z,
            radius,
            energy,
            transport,
        }): Parameters<SimDisasterArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.damage",
            json!({
                "x": x,
                "y": y,
                "z": z,
                "radius": radius.unwrap_or(3),
                "energy": energy.unwrap_or(2048),
            }),
            "sim_disaster",
        )
        .map(Json)
    }

    /// Best-effort law tool mapping to `sim.set_policy`.
    #[tool(
        name = "sim_law",
        description = "Best-effort mapping of law verbs to sim.set_policy."
    )]
    async fn sim_law(
        &self,
        Parameters(SimLawArgs {
            value,
            law,
            base_consumption_joules,
            transport,
        }): Parameters<SimLawArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let scarcity = value.unwrap_or(1.0);
        let mut params = serde_json::Map::new();
        params.insert("scarcity_multiplier".to_owned(), json!(scarcity));
        if let Some(base_consumption_joules) = base_consumption_joules {
            params.insert(
                "base_consumption_joules".to_owned(),
                json!(base_consumption_joules),
            );
        }
        forward_rpc(&transport, "sim.set_policy", Value::Object(params), "sim_law")
            .map_err(|err| format!("sim_law via {}: {err}", law))
            .map(Json)
    }

    /// Blind implementation: `sim.undo` has no dedicated JSON-RPC method yet.
    #[tool(
        name = "sim_undo",
        description = "sim.undo is unavailable on the current JSON-RPC surface."
    )]
    async fn sim_undo(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        Ok(Json(RpcForwardResult {
            method: "sim_undo".to_string(),
            url: transport.resolve_config().ws_url(),
            result: json!({
                "unavailable": true,
                "reason": "sim.undo has no wire method on this branch",
            }),
            harness_version: crate::HARNESS_VERSION,
        }))
    }

    /// Alias to `sim.spawn_civilian` for grouped organism spawning.
    #[tool(
        name = "sim_spawn_organism",
        description = "Best-effort grouped spawn fallback using repeated sim.spawn_civilian."
    )]
    async fn sim_spawn_organism(
        &self,
        Parameters(SimSpawnOrganismArgs {
            count,
            x,
            y,
            faction,
            transport,
        }): Parameters<SimSpawnOrganismArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        let mut last = None;
        for _ in 0..count.max(1) {
            last = Some(
                forward_rpc(
                    &transport,
                    "sim.spawn_civilian",
                    json!({
                        "x": x,
                        "y": y,
                        "faction": faction.unwrap_or(0),
                    }),
                    "sim_spawn_organism",
                )?,
            );
        }
        match last {
            Some(value) => Ok(Json(value)),
            None => Ok(Json(RpcForwardResult {
                method: "sim_spawn_organism".to_owned(),
                url: transport.resolve_config().ws_url(),
                result: json!({ "accepted": false, "count": 0 }),
                harness_version: crate::HARNESS_VERSION,
            })),
        }
    }

    /// Alias to `sim.save.slot`.
    #[tool(
        name = "sim_save_slot",
        description = "Alias for save.slot."
    )]
    async fn sim_save_slot(
        &self,
        Parameters(SaveSlotArgs { slot_name, transport }): Parameters<SaveSlotArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "save.slot",
            json!({ "slot_name": slot_name }),
            "sim_save_slot",
        )
        .map(Json)
    }

    /// Alias to `save.load`.
    #[tool(
        name = "sim_load_slot",
        description = "Alias for save.load."
    )]
    async fn sim_load_slot(
        &self,
        Parameters(SaveSlotArgs { slot_name, transport }): Parameters<SaveSlotArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "save.load",
            json!({ "slot_name": slot_name }),
            "sim_load_slot",
        )
        .map(Json)
    }

    /// Alias to `save.list`.
    #[tool(
        name = "sim_list_saves",
        description = "Alias for save.list."
    )]
    async fn sim_list_saves(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "save.list", json!({}), "sim_list_saves").map(Json)
    }

    /// Alias to `sim.save_replay`.
    #[tool(
        name = "sim_save_replay",
        description = "Alias for sim.save_replay."
    )]
    async fn sim_save_replay(
        &self,
        Parameters(SaveReplayArgs { path, transport }): Parameters<SaveReplayArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.save_replay",
            json!({ "path": path }),
            "sim_save_replay",
        )
        .map(Json)
    }

    /// Alias to `sim.load_replay`.
    #[tool(
        name = "sim_load_replay",
        description = "Alias for sim.load_replay."
    )]
    async fn sim_load_replay(
        &self,
        Parameters(SaveReplayArgs { path, transport }): Parameters<SaveReplayArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.load_replay",
            json!({ "path": path }),
            "sim_load_replay",
        )
        .map(Json)
    }

    /// Alias to `sim.subscribe`.
    #[tool(
        name = "sim_subscribe",
        description = "Alias for sim.subscribe."
    )]
    async fn sim_subscribe(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.subscribe", json!({}), "sim_subscribe").map(Json)
    }

    /// Alias to `sim.unsubscribe`.
    #[tool(
        name = "sim_unsubscribe",
        description = "Alias for sim.unsubscribe."
    )]
    async fn sim_unsubscribe(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(&transport, "sim.unsubscribe", json!({}), "sim_unsubscribe").map(Json)
    }

    /// Alias to `sim.update_subscription`.
    #[tool(
        name = "sim_update_subscription",
        description = "Alias for sim.update_subscription."
    )]
    async fn sim_update_subscription(
        &self,
        Parameters(transport): Parameters<RpcArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.update_subscription",
            json!({}),
            "sim_update_subscription",
        )
        .map(Json)
    }

    /// Alias to `sim.damage`.
    #[tool(
        name = "sim_damage",
        description = "Alias for sim.damage."
    )]
    async fn sim_damage(
        &self,
        Parameters(SimDamageArgs {
            x,
            y,
            z,
            radius,
            energy,
            transport,
        }): Parameters<SimDamageArgs>,
    ) -> Result<Json<RpcForwardResult>, String> {
        forward_rpc(
            &transport,
            "sim.damage",
            json!({
                "x": x,
                "y": y,
                "z": z,
                "radius": radius,
                "energy": energy,
            }),
            "sim_damage",
        )
        .map(Json)
    }
}

#[tool_handler]
impl rmcp::ServerHandler for CivisMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
    }
}

/// Public shim that re-exposes the macro-generated `tool_router` inherent
/// method across the `lib`/`server` module boundary (the macro emits the
/// method as `pub(self)`, which is invisible from sibling modules).
pub fn registered_router() -> ToolRouter<CivisMcpServer> {
    CivisMcpServer::tool_router()
}
