#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DINOForge.SDK.Dependencies;
using FluentAssertions;
using Xunit;

namespace DINOForge.Tests.SDK;

[Trait("Category", "SDK")]
public sealed class PackSubmoduleManagerCoverageTests : IDisposable
{
    private readonly List<string> _tempDirectories = new();

    [Fact]
    public async Task AddPackAsync_WithEmptyRepositoryUrl_ThrowsArgumentException()
    {
        string workingDirectory = CreateDirectory();
        PackSubmoduleManager manager = new(workingDirectory);

        Func<Task> action = () => manager.AddPackAsync(string.Empty);

        ArgumentException exception = (await action.Should().ThrowAsync<ArgumentException>()).Which;
        exception.ParamName.Should().Be("repoUrl");
    }

    [Fact]
    public void ListPacks_WithMixedGitModules_ReturnsOnlyPackEntries()
    {
        string workingDirectory = CreateDirectory();
        string gitmodulesPath = Path.Combine(workingDirectory, ".gitmodules");

        File.WriteAllText(
            gitmodulesPath,
            string.Join(
                Environment.NewLine,
                new[]
                {
                    "[submodule \"packs/alpha\"]",
                    "\tpath = packs/alpha",
                    "\turl = https://example.com/alpha.git",
                    "",
                    "[submodule \"tools/local\"]",
                    "\tpath = tools/local",
                    "\turl = https://example.com/tools.git",
                    "",
                    "[submodule \"packs/beta\"]",
                    "\tpath = packs/beta",
                    "\turl = https://example.com/beta.git",
                }) + Environment.NewLine);

        PackSubmoduleManager manager = new(workingDirectory);

        List<PackSubmoduleEntry> entries = manager.ListPacks();

        entries.Should().HaveCount(2);
        entries.Select(entry => entry.Path).Should().ContainInOrder("packs/alpha", "packs/beta");
        entries.Should().ContainSingle(entry => entry.Path == "packs/alpha" && entry.Url == "https://example.com/alpha.git");
        entries.Should().ContainSingle(entry => entry.Path == "packs/beta" && entry.Url == "https://example.com/beta.git");
    }

    [Fact]
    public void ReadLockFile_WithCommentsAndMalformedLines_ParsesOnlyValidEntries()
    {
        string workingDirectory = CreateDirectory();
        string lockPath = Path.Combine(workingDirectory, "packs.lock");

        File.WriteAllText(
            lockPath,
            string.Join(
                Environment.NewLine,
                new[]
                {
                    "# packs.lock - generated by dinoforge pack lock",
                    "",
                    "packs/alpha 123456789abc",
                    "packs/beta    fedcba987654",
                    "malformed-line",
                    "packs/gamma extra tokens ignored",
                    "   # indented comment",
                    "",
                }) + Environment.NewLine);

        PackSubmoduleManager manager = new(workingDirectory);

        Dictionary<string, string> entries = manager.ReadLockFile();

        entries.Should().HaveCount(2);
        entries.Should().ContainKey("packs/alpha").WhoseValue.Should().Be("123456789abc");
        entries.Should().ContainKey("packs/beta").WhoseValue.Should().Be("fedcba987654");
        entries.Should().NotContainKey("malformed-line");
        entries.Should().NotContainKey("packs/gamma");
    }

    [Fact]
    public void ReadLockFile_WhenMissing_ReturnsEmptyDictionary()
    {
        string workingDirectory = CreateDirectory();
        PackSubmoduleManager manager = new(workingDirectory);

        Dictionary<string, string> entries = manager.ReadLockFile();

        entries.Should().BeEmpty();
    }

    public void Dispose()
    {
        foreach (string directory in _tempDirectories)
        {
            try
            {
                if (Directory.Exists(directory))
                {
                    Directory.Delete(directory, recursive: true);
                }
            }
            catch
            {
                // Best-effort cleanup for temp test artifacts.
            }
        }

        _tempDirectories.Clear();
    }

    private string CreateDirectory()
    {
        string directory = Path.Combine(Path.GetTempPath(), "dinoforge_packsubmodule_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        _tempDirectories.Add(directory);
        return directory;
    }
}
